/* The following code was generated by JFlex 1.4.2 on 20/11/2025 12:14 */

/* Boogie 2 lexer */
package ultimate.parser;
import com.github.jhoenicke.javacup.runtime.Symbol;

/**
 * This is a autogenerated lexer for Boogie 2.
 * It is generated from Boogie.flex by JFlex.
 */

public class Lexer implements com.github.jhoenicke.javacup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\65\1\103"+
    "\2\6\1\71\1\73\1\6\1\46\1\47\1\5\1\67\1\55\1\70"+
    "\1\12\1\4\1\10\11\11\1\53\1\56\1\61\1\57\1\62\1\6"+
    "\1\0\32\6\1\50\1\104\1\51\2\6\1\0\1\30\1\13\1\21"+
    "\1\34\1\20\1\25\1\43\1\40\1\27\1\42\1\41\1\35\1\32"+
    "\1\23\1\22\1\17\1\36\1\33\1\24\1\15\1\26\1\14\1\37"+
    "\1\31\1\16\1\6\1\52\1\75\1\54\1\6\53\0\1\6\1\0"+
    "\1\72\10\0\1\6\4\0\1\6\5\0\27\6\1\0\37\6\1\0"+
    "\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6\1\0\1\6\201\0"+
    "\5\6\1\0\2\6\2\0\4\6\1\0\1\6\6\0\1\6\1\0"+
    "\3\6\1\0\1\6\1\0\24\6\1\0\123\6\1\0\213\6\10\0"+
    "\246\6\1\0\46\6\2\0\1\6\7\0\47\6\110\0\33\6\5\0"+
    "\3\6\55\0\53\6\25\0\12\7\4\0\2\6\1\0\143\6\1\0"+
    "\1\6\17\0\2\6\7\0\2\6\12\7\3\6\2\0\1\6\20\0"+
    "\1\6\1\0\36\6\35\0\131\6\13\0\1\6\16\0\12\7\41\6"+
    "\11\0\2\6\4\0\1\6\5\0\26\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\27\0\31\6\7\0\13\6\65\0\25\6\1\0\10\6"+
    "\106\0\66\6\3\0\1\6\22\0\1\6\7\0\12\6\4\0\12\7"+
    "\1\0\20\6\4\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6"+
    "\1\0\1\6\3\0\4\6\3\0\1\6\20\0\1\6\15\0\2\6"+
    "\1\0\3\6\4\0\12\7\2\6\12\0\1\6\10\0\6\6\4\0"+
    "\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0\2\6\1\0"+
    "\2\6\37\0\4\6\1\0\1\6\7\0\12\7\2\0\3\6\20\0"+
    "\11\6\1\0\3\6\1\0\26\6\1\0\7\6\1\0\2\6\1\0"+
    "\5\6\3\0\1\6\22\0\1\6\17\0\2\6\4\0\12\7\11\0"+
    "\1\6\13\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0"+
    "\2\6\1\0\5\6\3\0\1\6\36\0\2\6\1\0\3\6\4\0"+
    "\12\7\1\0\1\6\21\0\1\6\1\0\6\6\3\0\3\6\1\0"+
    "\4\6\3\0\2\6\1\0\1\6\1\0\2\6\3\0\2\6\3\0"+
    "\3\6\3\0\14\6\26\0\1\6\25\0\12\7\25\0\10\6\1\0"+
    "\3\6\1\0\27\6\1\0\20\6\3\0\1\6\32\0\3\6\5\0"+
    "\2\6\4\0\12\7\20\0\1\6\4\0\10\6\1\0\3\6\1\0"+
    "\27\6\1\0\12\6\1\0\5\6\3\0\1\6\40\0\1\6\1\0"+
    "\2\6\4\0\12\7\1\0\2\6\22\0\10\6\1\0\3\6\1\0"+
    "\51\6\2\0\1\6\20\0\1\6\5\0\3\6\10\0\3\6\4\0"+
    "\12\7\12\0\6\6\5\0\22\6\3\0\30\6\1\0\11\6\1\0"+
    "\1\6\2\0\7\6\37\0\12\7\21\0\60\6\1\0\2\6\14\0"+
    "\7\6\11\0\12\7\47\0\2\6\1\0\1\6\2\0\2\6\1\0"+
    "\1\6\2\0\1\6\6\0\4\6\1\0\7\6\1\0\3\6\1\0"+
    "\1\6\1\0\1\6\2\0\2\6\1\0\4\6\1\0\2\6\11\0"+
    "\1\6\2\0\5\6\1\0\1\6\11\0\12\7\2\0\4\6\40\0"+
    "\1\6\37\0\12\7\26\0\10\6\1\0\44\6\33\0\5\6\163\0"+
    "\53\6\24\0\1\6\12\7\6\0\6\6\4\0\4\6\3\0\1\6"+
    "\3\0\2\6\7\0\3\6\4\0\15\6\14\0\1\6\1\0\12\7"+
    "\6\0\46\6\1\0\1\6\5\0\1\6\2\0\53\6\1\0\u014d\6"+
    "\1\0\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0\51\6"+
    "\1\0\4\6\2\0\41\6\1\0\4\6\2\0\7\6\1\0\1\6"+
    "\1\0\4\6\2\0\17\6\1\0\71\6\1\0\4\6\2\0\103\6"+
    "\45\0\20\6\20\0\126\6\2\0\6\6\3\0\u026c\6\2\0\21\6"+
    "\1\0\32\6\5\0\113\6\6\0\10\6\7\0\15\6\1\0\4\6"+
    "\16\0\22\6\16\0\22\6\16\0\15\6\1\0\3\6\17\0\64\6"+
    "\43\0\1\6\4\0\1\6\3\0\12\7\46\0\12\7\6\0\130\6"+
    "\10\0\5\6\2\0\42\6\1\0\1\6\5\0\106\6\12\0\37\6"+
    "\47\0\12\7\36\6\2\0\5\6\13\0\54\6\4\0\32\6\6\0"+
    "\12\7\46\0\27\6\11\0\65\6\53\0\12\7\6\0\12\7\15\0"+
    "\1\6\135\0\57\6\21\0\7\6\4\0\12\7\51\0\36\6\15\0"+
    "\2\6\12\7\54\6\32\0\44\6\34\0\12\7\3\0\3\6\12\7"+
    "\44\6\2\0\11\6\140\0\4\6\1\0\4\6\3\0\2\6\11\0"+
    "\300\6\100\0\u0116\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0"+
    "\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0"+
    "\65\6\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0"+
    "\4\6\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\45\0"+
    "\1\102\116\0\1\6\15\0\1\6\20\0\15\6\145\0\1\6\4\0"+
    "\1\6\2\0\12\6\1\0\1\6\3\0\5\6\6\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\4\6\1\0\13\6\2\0\4\6\5\0"+
    "\5\6\4\0\1\6\64\0\2\6\113\0\1\100\1\0\1\77\1\0"+
    "\1\101\53\0\1\44\2\0\1\45\43\0\1\74\1\76\53\0\1\60"+
    "\13\0\1\66\3\0\1\63\1\64\u099a\0\57\6\1\0\57\6\1\0"+
    "\205\6\6\0\4\6\3\0\2\6\14\0\46\6\1\0\1\6\5\0"+
    "\1\6\2\0\70\6\7\0\1\6\20\0\27\6\11\0\7\6\1\0"+
    "\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\7\6\120\0\1\6\u01d5\0\2\6\52\0\5\6\5\0"+
    "\2\6\4\0\126\6\6\0\3\6\1\0\132\6\1\0\4\6\5\0"+
    "\52\6\2\0\136\6\21\0\33\6\65\0\20\6\u0200\0\u19b6\6\112\0"+
    "\u51f0\6\20\0\u048d\6\103\0\56\6\2\0\u010d\6\3\0\20\6\12\7"+
    "\2\6\24\0\57\6\20\0\37\6\2\0\106\6\61\0\11\6\2\0"+
    "\147\6\2\0\44\6\1\0\10\6\77\0\13\6\1\0\3\6\1\0"+
    "\4\6\1\0\27\6\35\0\64\6\16\0\62\6\34\0\12\7\30\0"+
    "\6\6\3\0\1\6\1\0\1\6\2\0\12\7\34\6\12\0\27\6"+
    "\31\0\35\6\7\0\57\6\34\0\1\6\12\7\6\0\5\6\1\0"+
    "\12\6\12\7\5\6\1\0\51\6\27\0\3\6\1\0\10\6\4\0"+
    "\12\7\6\0\27\6\3\0\1\6\3\0\62\6\1\0\1\6\3\0"+
    "\2\6\2\0\5\6\2\0\1\6\1\0\1\6\30\0\3\6\2\0"+
    "\13\6\7\0\3\6\14\0\6\6\2\0\6\6\2\0\6\6\11\0"+
    "\7\6\1\0\7\6\1\0\53\6\1\0\12\6\12\0\163\6\15\0"+
    "\12\7\6\0\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0\u016e\6\2\0"+
    "\152\6\46\0\7\6\14\0\5\6\5\0\1\6\1\0\12\6\1\0"+
    "\15\6\1\0\5\6\1\0\1\6\1\0\2\6\1\0\2\6\1\0"+
    "\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0\14\6\164\0"+
    "\5\6\1\0\207\6\23\0\12\7\7\0\32\6\6\0\32\6\13\0"+
    "\131\6\3\0\6\6\2\0\6\6\2\0\6\6\2\0\3\6\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\2\6\22\5"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\30\1\1"+
    "\1\35\1\1\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\2\3\0\25\5\1\47\13\5"+
    "\1\0\1\50\1\51\1\52\1\26\1\53\1\54\1\55"+
    "\1\56\1\57\1\0\1\60\1\0\2\61\2\5\1\62"+
    "\12\5\1\63\7\5\1\64\5\5\1\65\3\5\1\66"+
    "\5\5\1\15\1\0\1\40\2\67\1\70\1\5\1\71"+
    "\1\72\1\73\3\5\1\74\2\5\1\75\1\5\1\76"+
    "\3\5\1\77\13\5\1\100\4\5\1\101\1\102\1\15"+
    "\1\50\1\0\1\103\3\5\1\104\4\5\1\105\4\5"+
    "\1\106\3\5\1\107\3\5\1\110\1\111\1\112\1\15"+
    "\2\5\1\10\1\5\1\7\1\5\1\113\1\114\2\5"+
    "\1\115\1\116\1\117\1\120\1\5\1\121\1\5\3\15"+
    "\1\50\1\5\1\122\5\5\1\123\1\5\1\0\1\50"+
    "\1\5\1\124\1\125\2\5\1\126\1\127\1\0\1\130"+
    "\1\131\5\5\1\132";

  private static int [] zzUnpackAction() {
    int [] result = new int[270];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\105\0\212\0\317\0\212\0\u0114\0\212\0\u0159"+
    "\0\u019e\0\u01e3\0\u0228\0\u026d\0\u02b2\0\u02f7\0\u033c\0\u0381"+
    "\0\u03c6\0\u040b\0\u0450\0\u0495\0\u04da\0\u051f\0\u0564\0\u05a9"+
    "\0\u05ee\0\u0633\0\u0678\0\u06bd\0\212\0\212\0\212\0\212"+
    "\0\212\0\212\0\u0702\0\u0747\0\212\0\212\0\212\0\u078c"+
    "\0\212\0\u07d1\0\u0816\0\212\0\212\0\u085b\0\212\0\u08a0"+
    "\0\212\0\212\0\212\0\u08e5\0\212\0\u092a\0\212\0\212"+
    "\0\212\0\212\0\212\0\212\0\u096f\0\212\0\u09b4\0\u09f9"+
    "\0\u0a3e\0\u0a83\0\u0ac8\0\u0b0d\0\u0b52\0\u0b97\0\u0bdc\0\u0c21"+
    "\0\u0c66\0\u0cab\0\u0cf0\0\u0d35\0\u0d7a\0\u0dbf\0\u0e04\0\u0e49"+
    "\0\u0e8e\0\u0ed3\0\u0f18\0\u0f5d\0\u0fa2\0\u0fe7\0\u102c\0\u1071"+
    "\0\u0159\0\u10b6\0\u10fb\0\u1140\0\u1185\0\u11ca\0\u120f\0\u1254"+
    "\0\u1299\0\u12de\0\u1323\0\u1368\0\u13ad\0\212\0\u13f2\0\212"+
    "\0\u1437\0\212\0\212\0\212\0\212\0\212\0\u147c\0\u0a83"+
    "\0\u14c1\0\u0159\0\u1506\0\u154b\0\u1590\0\u0159\0\u15d5\0\u161a"+
    "\0\u165f\0\u16a4\0\u16e9\0\u172e\0\u1773\0\u17b8\0\u17fd\0\u1842"+
    "\0\u0159\0\u1887\0\u18cc\0\u1911\0\u1956\0\u199b\0\u19e0\0\u1a25"+
    "\0\u0159\0\u1a6a\0\u1aaf\0\u1af4\0\u1b39\0\u1b7e\0\u1bc3\0\u1c08"+
    "\0\u1c4d\0\u1c92\0\u0159\0\u1cd7\0\u1d1c\0\u1d61\0\u1da6\0\u1deb"+
    "\0\u1e30\0\u1e75\0\u1eba\0\212\0\u1eff\0\u0159\0\u1f44\0\u0159"+
    "\0\u0159\0\u0159\0\u1f89\0\u1fce\0\u2013\0\u0159\0\u2058\0\u209d"+
    "\0\u0159\0\u20e2\0\u0159\0\u2127\0\u216c\0\u21b1\0\u0159\0\u21f6"+
    "\0\u223b\0\u2280\0\u22c5\0\u230a\0\u234f\0\u2394\0\u23d9\0\u241e"+
    "\0\u2463\0\u24a8\0\u0159\0\u24ed\0\u2532\0\u2577\0\u25bc\0\u0159"+
    "\0\u0159\0\u2601\0\u1e30\0\u2646\0\u0159\0\u268b\0\u26d0\0\u2715"+
    "\0\u0159\0\u275a\0\u279f\0\u27e4\0\u2829\0\u0159\0\u286e\0\u28b3"+
    "\0\u28f8\0\u293d\0\u0159\0\u2982\0\u29c7\0\u2a0c\0\u0159\0\u2a51"+
    "\0\u2a96\0\u2adb\0\u0159\0\u0159\0\u0159\0\u2b20\0\u2b65\0\u2baa"+
    "\0\u0159\0\u2bef\0\u0159\0\u2c34\0\u0159\0\u0159\0\u2c79\0\u2cbe"+
    "\0\u0159\0\u0159\0\u0159\0\u0159\0\u2d03\0\u2d48\0\u2d8d\0\u2dd2"+
    "\0\u2e17\0\u2e5c\0\u2b20\0\u2ea1\0\u0159\0\u2ee6\0\u2f2b\0\u2f70"+
    "\0\u2fb5\0\u2ffa\0\u0159\0\u303f\0\u3084\0\u1e75\0\u30c9\0\u0159"+
    "\0\u0159\0\u310e\0\u3153\0\u0159\0\u0159\0\u3198\0\u0159\0\u0159"+
    "\0\u31dd\0\u3222\0\u3267\0\u32ac\0\u32f1\0\u0159";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[270];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\12\1\10\1\13\1\14\1\15\1\10\1\16\1\17"+
    "\1\20\1\21\2\10\1\22\1\23\1\24\1\25\1\10"+
    "\1\26\1\27\1\30\2\10\1\31\1\32\1\10\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\1\74\1\10\1\75\2\3\100\75\1\76\1\77\107\0"+
    "\1\5\106\0\1\100\1\101\105\0\36\10\40\0\1\10"+
    "\12\0\1\102\1\103\101\0\2\12\1\102\1\103\77\0"+
    "\6\10\1\104\5\10\1\105\10\10\1\106\10\10\40\0"+
    "\1\10\6\0\22\10\1\107\13\10\40\0\1\10\6\0"+
    "\10\10\1\110\14\10\1\111\4\10\1\112\3\10\40\0"+
    "\1\10\6\0\25\10\1\113\10\10\40\0\1\10\6\0"+
    "\15\10\1\114\5\10\1\115\3\10\1\116\6\10\40\0"+
    "\1\10\6\0\14\10\1\117\5\10\1\120\13\10\40\0"+
    "\1\10\6\0\27\10\1\121\6\10\40\0\1\10\6\0"+
    "\14\10\1\122\3\10\1\123\1\124\1\125\2\10\1\126"+
    "\10\10\40\0\1\10\6\0\15\10\1\127\20\10\40\0"+
    "\1\10\6\0\15\10\1\130\1\10\1\131\4\10\1\132"+
    "\11\10\40\0\1\10\6\0\7\10\1\133\6\10\1\134"+
    "\4\10\1\135\12\10\40\0\1\10\6\0\14\10\1\136"+
    "\21\10\40\0\1\10\6\0\12\10\1\137\23\10\40\0"+
    "\1\10\6\0\21\10\1\140\14\10\40\0\1\10\6\0"+
    "\32\10\1\141\3\10\40\0\1\10\6\0\22\10\1\142"+
    "\13\10\40\0\1\10\6\0\14\10\1\143\21\10\40\0"+
    "\1\10\6\0\14\10\1\144\21\10\40\0\1\10\1\0"+
    "\3\43\1\145\46\0\1\146\104\0\1\73\3\0\1\51"+
    "\104\0\1\147\100\0\1\150\3\0\1\151\104\0\1\55"+
    "\104\0\1\57\114\0\1\152\110\0\1\65\106\0\1\67"+
    "\7\0\1\75\2\0\100\75\17\0\1\153\5\0\1\154"+
    "\7\0\1\155\47\0\1\156\1\0\1\100\1\4\1\5"+
    "\102\100\5\101\1\157\77\101\10\0\2\160\107\0\1\161"+
    "\76\0\2\10\1\162\1\163\32\10\40\0\1\10\6\0"+
    "\14\10\1\164\21\10\40\0\1\10\6\0\12\10\1\165"+
    "\23\10\40\0\1\10\6\0\25\10\1\166\10\10\40\0"+
    "\1\10\6\0\11\10\1\167\24\10\40\0\1\10\6\0"+
    "\20\10\1\170\15\10\40\0\1\10\6\0\12\10\1\171"+
    "\23\10\40\0\1\10\6\0\14\10\1\172\21\10\40\0"+
    "\1\10\6\0\16\10\1\173\17\10\40\0\1\10\6\0"+
    "\21\10\1\174\14\10\40\0\1\10\6\0\16\10\1\175"+
    "\17\10\40\0\1\10\6\0\15\10\1\176\6\10\1\177"+
    "\11\10\40\0\1\10\6\0\27\10\1\200\6\10\40\0"+
    "\1\10\6\0\26\10\1\201\7\10\40\0\1\10\6\0"+
    "\25\10\1\202\10\10\40\0\1\10\6\0\15\10\1\203"+
    "\20\10\40\0\1\10\6\0\15\10\1\204\20\10\40\0"+
    "\1\10\6\0\27\10\1\205\6\10\40\0\1\10\6\0"+
    "\12\10\1\206\23\10\40\0\1\10\6\0\21\10\1\207"+
    "\14\10\40\0\1\10\6\0\6\10\1\210\1\211\26\10"+
    "\40\0\1\10\6\0\11\10\1\212\24\10\40\0\1\10"+
    "\6\0\14\10\1\213\21\10\40\0\1\10\6\0\10\10"+
    "\1\214\5\10\1\215\17\10\40\0\1\10\6\0\21\10"+
    "\1\216\14\10\40\0\1\10\6\0\26\10\1\217\7\10"+
    "\40\0\1\10\6\0\7\10\1\220\12\10\1\221\5\10"+
    "\1\222\5\10\40\0\1\10\6\0\6\10\1\223\27\10"+
    "\40\0\1\10\6\0\12\10\1\224\6\10\1\225\14\10"+
    "\40\0\1\10\6\0\6\10\1\226\27\10\40\0\1\10"+
    "\6\0\21\10\1\227\14\10\40\0\1\10\6\0\7\10"+
    "\1\230\26\10\40\0\1\10\4\0\1\231\1\232\161\0"+
    "\1\70\101\0\1\233\25\0\4\101\1\5\1\157\77\101"+
    "\10\0\1\234\1\235\101\0\2\10\2\163\32\10\40\0"+
    "\1\10\6\0\27\10\1\236\6\10\40\0\1\10\6\0"+
    "\22\10\1\237\13\10\40\0\1\10\6\0\12\10\1\240"+
    "\23\10\40\0\1\10\6\0\12\10\1\241\23\10\40\0"+
    "\1\10\6\0\15\10\1\242\20\10\40\0\1\10\6\0"+
    "\13\10\1\243\22\10\40\0\1\10\6\0\20\10\1\244"+
    "\15\10\40\0\1\10\6\0\16\10\1\245\17\10\40\0"+
    "\1\10\6\0\12\10\1\246\23\10\40\0\1\10\6\0"+
    "\16\10\1\247\17\10\40\0\1\10\6\0\11\10\1\250"+
    "\24\10\40\0\1\10\6\0\27\10\1\251\6\10\40\0"+
    "\1\10\6\0\22\10\1\252\10\10\1\253\2\10\40\0"+
    "\1\10\6\0\13\10\1\254\22\10\40\0\1\10\6\0"+
    "\21\10\1\255\14\10\40\0\1\10\6\0\16\10\1\256"+
    "\17\10\40\0\1\10\6\0\12\10\1\257\23\10\40\0"+
    "\1\10\6\0\30\10\1\260\5\10\40\0\1\10\6\0"+
    "\22\10\1\261\13\10\40\0\1\10\6\0\27\10\1\262"+
    "\6\10\40\0\1\10\6\0\24\10\1\263\11\10\40\0"+
    "\1\10\6\0\15\10\1\264\20\10\40\0\1\10\6\0"+
    "\12\10\1\265\5\10\1\266\1\267\14\10\40\0\1\10"+
    "\6\0\14\10\1\270\21\10\40\0\1\10\6\0\21\10"+
    "\1\271\14\10\40\0\1\10\6\0\20\10\1\272\15\10"+
    "\40\0\1\10\6\0\27\10\1\273\6\10\40\0\1\10"+
    "\6\0\20\10\1\274\15\10\40\0\1\10\6\0\25\10"+
    "\1\275\10\10\40\0\1\10\6\0\27\10\1\276\6\10"+
    "\40\0\1\10\6\0\14\10\1\277\21\10\40\0\1\10"+
    "\6\0\15\10\1\300\20\10\40\0\1\10\6\0\14\10"+
    "\1\301\21\10\40\0\1\10\1\231\2\43\1\231\1\302"+
    "\46\231\1\303\31\231\5\232\1\304\77\232\62\0\1\72"+
    "\32\0\2\235\101\0\33\10\1\305\2\10\40\0\1\10"+
    "\6\0\12\10\1\306\23\10\40\0\1\10\6\0\25\10"+
    "\1\307\10\10\40\0\1\10\6\0\7\10\1\310\26\10"+
    "\40\0\1\10\6\0\7\10\1\311\26\10\40\0\1\10"+
    "\6\0\27\10\1\312\6\10\40\0\1\10\6\0\27\10"+
    "\1\313\6\10\40\0\1\10\6\0\7\10\1\314\26\10"+
    "\40\0\1\10\6\0\7\10\1\315\26\10\40\0\1\10"+
    "\6\0\12\10\1\316\23\10\40\0\1\10\6\0\20\10"+
    "\1\317\15\10\40\0\1\10\6\0\25\10\1\320\10\10"+
    "\40\0\1\10\6\0\12\10\1\321\23\10\40\0\1\10"+
    "\6\0\21\10\1\322\14\10\40\0\1\10\6\0\13\10"+
    "\1\323\22\10\40\0\1\10\6\0\25\10\1\324\10\10"+
    "\40\0\1\10\6\0\24\10\1\325\11\10\40\0\1\10"+
    "\6\0\35\10\1\326\40\0\1\10\6\0\24\10\1\327"+
    "\11\10\40\0\1\10\6\0\17\10\1\330\16\10\40\0"+
    "\1\10\6\0\25\10\1\331\10\10\40\0\1\10\6\0"+
    "\21\10\1\332\14\10\40\0\1\10\6\0\12\10\1\333"+
    "\23\10\40\0\1\10\6\0\12\10\1\334\23\10\40\0"+
    "\1\10\6\0\13\10\1\335\22\10\40\0\1\10\1\231"+
    "\2\43\1\231\1\302\1\336\45\231\1\303\31\231\4\232"+
    "\1\43\1\304\77\232\6\0\26\10\1\337\7\10\40\0"+
    "\1\10\6\0\12\10\1\340\23\10\40\0\1\10\6\0"+
    "\16\10\1\341\17\10\40\0\1\10\6\0\12\10\1\342"+
    "\23\10\40\0\1\10\6\0\27\10\1\343\6\10\40\0"+
    "\1\10\6\0\21\10\1\344\14\10\40\0\1\10\6\0"+
    "\12\10\1\345\23\10\40\0\1\10\6\0\12\10\1\346"+
    "\23\10\40\0\1\10\6\0\21\10\1\347\14\10\40\0"+
    "\1\10\6\0\24\10\1\350\11\10\40\0\1\10\6\0"+
    "\13\10\1\351\22\10\40\0\1\10\6\0\7\10\1\352"+
    "\26\10\40\0\1\10\6\0\12\10\1\353\23\10\40\0"+
    "\1\10\6\0\15\10\1\354\20\10\40\0\1\10\6\0"+
    "\21\10\1\355\14\10\40\0\1\10\6\0\15\10\1\356"+
    "\20\10\40\0\1\10\6\0\25\10\1\357\10\10\40\0"+
    "\1\10\1\336\2\360\1\336\1\361\1\362\45\336\1\363"+
    "\31\336\6\0\20\10\1\364\15\10\40\0\1\10\6\0"+
    "\16\10\1\365\17\10\40\0\1\10\6\0\7\10\1\366"+
    "\26\10\40\0\1\10\6\0\14\10\1\367\21\10\40\0"+
    "\1\10\6\0\22\10\1\370\13\10\40\0\1\10\6\0"+
    "\12\10\1\371\23\10\40\0\1\10\6\0\12\10\1\372"+
    "\23\10\40\0\1\10\6\0\16\10\1\373\17\10\40\0"+
    "\1\10\6\0\12\10\1\374\23\10\40\0\1\10\1\232"+
    "\3\360\1\375\1\304\45\232\1\376\31\232\1\336\2\360"+
    "\1\336\1\361\46\336\1\363\32\336\2\360\1\336\1\302"+
    "\1\362\45\336\1\363\31\336\6\0\25\10\1\377\10\10"+
    "\40\0\1\10\6\0\12\10\1\u0100\23\10\40\0\1\10"+
    "\6\0\15\10\1\u0101\20\10\40\0\1\10\6\0\15\10"+
    "\1\u0102\20\10\40\0\1\10\6\0\15\10\1\u0103\20\10"+
    "\40\0\1\10\6\0\16\10\1\u0104\17\10\40\0\1\10"+
    "\6\0\16\10\1\u0105\17\10\40\0\1\10\4\232\1\336"+
    "\1\u0106\77\232\6\0\12\10\1\u0107\23\10\40\0\1\10"+
    "\6\0\7\10\1\u0108\26\10\40\0\1\10\6\0\7\10"+
    "\1\u0109\26\10\40\0\1\10\4\232\1\360\1\304\77\232"+
    "\6\0\22\10\1\u010a\13\10\40\0\1\10\6\0\7\10"+
    "\1\u010b\26\10\40\0\1\10\6\0\21\10\1\u010c\14\10"+
    "\40\0\1\10\6\0\14\10\1\u010d\21\10\40\0\1\10"+
    "\6\0\15\10\1\u010e\20\10\40\0\1\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[13110];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\1\1\1\11\25\1\6\11"+
    "\2\1\3\11\1\1\1\11\2\1\2\11\1\1\1\11"+
    "\1\1\3\11\1\1\1\11\1\1\6\11\1\1\1\11"+
    "\2\1\3\0\41\1\1\0\1\11\1\1\1\11\1\1"+
    "\5\11\1\0\1\1\1\0\50\1\1\0\1\1\1\11"+
    "\47\1\1\0\70\1\1\0\10\1\1\0\10\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[270];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  private StringBuffer string = new StringBuffer();
  private BoogieSymbolFactory symFactory;
  
  public void setSymbolFactory(BoogieSymbolFactory factory) {
    symFactory = factory;
  }

  private Symbol symbol(int type) {
    return symFactory.newSymbol(yytext(), type, yyline+1, yycolumn, yyline+1, yycolumn+yylength());
  }
  private Symbol symbol(int type, String value) {
    return symFactory.newSymbol(value, type, yyline+1, yycolumn, yyline+1, yycolumn+yylength(), value);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1820) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public com.github.jhoenicke.javacup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 58: 
          { return symbol(LexerSymbols.TRUE);
          }
        case 91: break;
        case 85: 
          { return symbol(LexerSymbols.FUNCTION);
          }
        case 92: break;
        case 70: 
          { return symbol(LexerSymbols.ASYNC);
          }
        case 93: break;
        case 52: 
          { return symbol(LexerSymbols.INT);
          }
        case 94: break;
        case 29: 
          { return symbol(LexerSymbols.AND);
          }
        case 95: break;
        case 11: 
          { return symbol(LexerSymbols.LBKT);
          }
        case 96: break;
        case 27: 
          { return symbol(LexerSymbols.MINUS);
          }
        case 97: break;
        case 8: 
          { return symbol(LexerSymbols.EXISTS);
          }
        case 98: break;
        case 26: 
          { return symbol(LexerSymbols.PLUS);
          }
        case 99: break;
        case 39: 
          { return symbol(LexerSymbols.IF);
          }
        case 100: break;
        case 37: 
          { yybegin(YYINITIAL); 
                                   return symbol(LexerSymbols.ATTR_STRING, 
                                   string.toString().intern());
          }
        case 101: break;
        case 61: 
          { return symbol(LexerSymbols.CALL);
          }
        case 102: break;
        case 77: 
          { return symbol(LexerSymbols.ATOMIC);
          }
        case 103: break;
        case 3: 
          { return symbol(LexerSymbols.DIVIDE);
          }
        case 104: break;
        case 62: 
          { return symbol(LexerSymbols.FORK);
          }
        case 105: break;
        case 24: 
          { return symbol(LexerSymbols.NOT);
          }
        case 106: break;
        case 76: 
          { return symbol(LexerSymbols.UNIQUE);
          }
        case 107: break;
        case 10: 
          { return symbol(LexerSymbols.RPAR);
          }
        case 108: break;
        case 14: 
          { return symbol(LexerSymbols.COLON);
          }
        case 109: break;
        case 5: 
          { return symbol(LexerSymbols.ID, yytext().intern());
          }
        case 110: break;
        case 78: 
          { return symbol(LexerSymbols.ASSERT);
          }
        case 111: break;
        case 72: 
          { return symbol(LexerSymbols.WHERE);
          }
        case 112: break;
        case 45: 
          { string.append('\n');
          }
        case 113: break;
        case 66: 
          { return symbol(LexerSymbols.GOTO);
          }
        case 114: break;
        case 59: 
          { return symbol(LexerSymbols.THEN);
          }
        case 115: break;
        case 9: 
          { return symbol(LexerSymbols.LPAR);
          }
        case 116: break;
        case 47: 
          { string.append('\"');
          }
        case 117: break;
        case 49: 
          { return symbol(LexerSymbols.BVTYPE, yytext().intern());
          }
        case 118: break;
        case 87: 
          { return symbol(LexerSymbols.REQUIRES);
          }
        case 119: break;
        case 33: 
          { return symbol(LexerSymbols.IFF);
          }
        case 120: break;
        case 75: 
          { return symbol(LexerSymbols.FINITE);
          }
        case 121: break;
        case 73: 
          { return symbol(LexerSymbols.WHILE);
          }
        case 122: break;
        case 18: 
          { return symbol(LexerSymbols.EQUALS);
          }
        case 123: break;
        case 32: 
          { return symbol(LexerSymbols.EXPLIES);
          }
        case 124: break;
        case 46: 
          { string.append('\r');
          }
        case 125: break;
        case 50: 
          { return symbol(LexerSymbols.VAR);
          }
        case 126: break;
        case 35: 
          { string.setLength(0); yybegin(STRING);
          }
        case 127: break;
        case 16: 
          { return symbol(LexerSymbols.COMMA);
          }
        case 128: break;
        case 80: 
          { return symbol(LexerSymbols.ASSIGN);
          }
        case 129: break;
        case 51: 
          { return symbol(LexerSymbols.OLD);
          }
        case 130: break;
        case 44: 
          { string.append('\t');
          }
        case 131: break;
        case 56: 
          { return symbol(LexerSymbols.BOOL);
          }
        case 132: break;
        case 63: 
          { return symbol(LexerSymbols.FREE);
          }
        case 133: break;
        case 64: 
          { return symbol(LexerSymbols.REAL);
          }
        case 134: break;
        case 65: 
          { return symbol(LexerSymbols.JOIN);
          }
        case 135: break;
        case 90: 
          { return symbol(LexerSymbols.IMPLEMENTATION);
          }
        case 136: break;
        case 53: 
          { return symbol(LexerSymbols.MODKW);
          }
        case 137: break;
        case 79: 
          { return symbol(LexerSymbols.ASSUME);
          }
        case 138: break;
        case 86: 
          { return symbol(LexerSymbols.MODIFIES);
          }
        case 139: break;
        case 1: 
          { return symbol(LexerSymbols.error, yytext());
          }
        case 140: break;
        case 71: 
          { return symbol(LexerSymbols.AXIOM);
          }
        case 141: break;
        case 57: 
          { return symbol(LexerSymbols.TYPE);
          }
        case 142: break;
        case 40: 
          { return symbol(LexerSymbols.LBRCCOLON);
          }
        case 143: break;
        case 4: 
          { return symbol(LexerSymbols.TIMES);
          }
        case 144: break;
        case 22: 
          { return symbol(LexerSymbols.LTEQ);
          }
        case 145: break;
        case 34: 
          { return symbol(LexerSymbols.QSEP);
          }
        case 146: break;
        case 21: 
          { return symbol(LexerSymbols.GREATER);
          }
        case 147: break;
        case 41: 
          { return symbol(LexerSymbols.EQ);
          }
        case 148: break;
        case 74: 
          { return symbol(LexerSymbols.HAVOC);
          }
        case 149: break;
        case 6: 
          { return symbol(LexerSymbols.NUMBER, yytext().intern());
          }
        case 150: break;
        case 83: 
          { return symbol(LexerSymbols.RETURNS);
          }
        case 151: break;
        case 68: 
          { return symbol(LexerSymbols.CONST);
          }
        case 152: break;
        case 15: 
          { return symbol(LexerSymbols.RBRC);
          }
        case 153: break;
        case 20: 
          { return symbol(LexerSymbols.LESS);
          }
        case 154: break;
        case 38: 
          { string.append('\\');
          }
        case 155: break;
        case 88: 
          { return symbol(LexerSymbols.PROCEDURE);
          }
        case 156: break;
        case 84: 
          { return symbol(LexerSymbols.COMPLETE);
          }
        case 157: break;
        case 60: 
          { return symbol(LexerSymbols.ELSE);
          }
        case 158: break;
        case 13: 
          { return symbol(LexerSymbols.LBRC);
          }
        case 159: break;
        case 54: 
          { return symbol(LexerSymbols.DIV);
          }
        case 160: break;
        case 48: 
          { return symbol(LexerSymbols.REALNUMBER, yytext().intern());
          }
        case 161: break;
        case 23: 
          { return symbol(LexerSymbols.GTEQ);
          }
        case 162: break;
        case 28: 
          { return symbol(LexerSymbols.MOD);
          }
        case 163: break;
        case 82: 
          { return symbol(LexerSymbols.ENSURES);
          }
        case 164: break;
        case 69: 
          { return symbol(LexerSymbols.FALSE);
          }
        case 165: break;
        case 55: 
          { return symbol(LexerSymbols.BITVECTOR, yytext().intern());
          }
        case 166: break;
        case 7: 
          { return symbol(LexerSymbols.FORALL);
          }
        case 167: break;
        case 2: 
          { /* ignore */
          }
        case 168: break;
        case 89: 
          { return symbol(LexerSymbols.INVARIANT);
          }
        case 169: break;
        case 30: 
          { return symbol(LexerSymbols.OR);
          }
        case 170: break;
        case 36: 
          { string.append( yytext() );
          }
        case 171: break;
        case 67: 
          { return symbol(LexerSymbols.BREAK);
          }
        case 172: break;
        case 19: 
          { return symbol(LexerSymbols.COLONEQUALS);
          }
        case 173: break;
        case 42: 
          { return symbol(LexerSymbols.PARTORDER);
          }
        case 174: break;
        case 81: 
          { return symbol(LexerSymbols.RETURN);
          }
        case 175: break;
        case 25: 
          { return symbol(LexerSymbols.NEQ);
          }
        case 176: break;
        case 43: 
          { return symbol(LexerSymbols.CONCAT);
          }
        case 177: break;
        case 17: 
          { return symbol(LexerSymbols.SEMI);
          }
        case 178: break;
        case 12: 
          { return symbol(LexerSymbols.RBKT);
          }
        case 179: break;
        case 31: 
          { return symbol(LexerSymbols.IMPLIES);
          }
        case 180: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return symbol(LexerSymbols.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
