
//----------------------------------------------------
// The following code was generated by jh-javacup-1.2 20210807
// Thu Nov 20 12:14:27 CET 2025
//----------------------------------------------------

package ultimate.parser;

/** CUP generated class containing symbol constants. */
public class LexerSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int TYPE = 2;
  public static final int CONST = 3;
  public static final int FUNCTION = 4;
  public static final int AXIOM = 5;
  public static final int VAR = 6;
  public static final int PROCEDURE = 7;
  public static final int IMPLEMENTATION = 8;
  public static final int FINITE = 9;
  public static final int UNIQUE = 10;
  public static final int COMPLETE = 11;
  public static final int RETURNS = 12;
  public static final int WHERE = 13;
  public static final int FREE = 14;
  public static final int REQUIRES = 15;
  public static final int ENSURES = 16;
  public static final int MODIFIES = 17;
  public static final int INVARIANT = 18;
  public static final int OLD = 19;
  public static final int FORALL = 20;
  public static final int EXISTS = 21;
  public static final int BOOL = 22;
  public static final int INT = 23;
  public static final int REAL = 24;
  public static final int FALSE = 25;
  public static final int TRUE = 26;
  public static final int ASSUME = 27;
  public static final int ASSERT = 28;
  public static final int HAVOC = 29;
  public static final int FORK = 30;
  public static final int JOIN = 31;
  public static final int ASYNC = 32;
  public static final int CALL = 33;
  public static final int IF = 34;
  public static final int THEN = 35;
  public static final int ELSE = 36;
  public static final int WHILE = 37;
  public static final int BREAK = 38;
  public static final int RETURN = 39;
  public static final int GOTO = 40;
  public static final int ATOMIC = 41;
  public static final int COMMA = 42;
  public static final int COLON = 43;
  public static final int SEMI = 44;
  public static final int COLONEQUALS = 45;
  public static final int EQUALS = 46;
  public static final int ASSIGN = 47;
  public static final int LPAR = 48;
  public static final int RPAR = 49;
  public static final int LBKT = 50;
  public static final int RBKT = 51;
  public static final int LBRCCOLON = 52;
  public static final int LBRC = 53;
  public static final int RBRC = 54;
  public static final int LANG = 55;
  public static final int RANG = 56;
  public static final int LESS = 57;
  public static final int GREATER = 58;
  public static final int LTEQ = 59;
  public static final int GTEQ = 60;
  public static final int NEQ = 61;
  public static final int EQ = 62;
  public static final int PARTORDER = 63;
  public static final int PLUS = 64;
  public static final int MINUS = 65;
  public static final int TIMES = 66;
  public static final int DIVIDE = 67;
  public static final int MOD = 68;
  public static final int DIV = 69;
  public static final int MODKW = 70;
  public static final int QSEP = 71;
  public static final int NOT = 72;
  public static final int OR = 73;
  public static final int AND = 74;
  public static final int IMPLIES = 75;
  public static final int IFF = 76;
  public static final int EXPLIES = 77;
  public static final int CONCAT = 78;
  public static final int BVTYPE = 79;
  public static final int NUMBER = 80;
  public static final int REALNUMBER = 81;
  public static final int BITVECTOR = 82;
  public static final int ID = 83;
  public static final int ATTR_STRING = 84;
}

