/* ArrayType -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a array type which is a special form of a ast type.
 */
public class ArrayType extends ASTType {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(ArrayType.class);
    /**
     * The type params of this array type.
     */
    String[] typeParams;

    /**
     * The index types of this array type.
     */
    ASTType[] indexTypes;

    /**
     * The value type of this array type.
     */
    ASTType valueType;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param typeParams the type params of this array type.
     * @param indexTypes the index types of this array type.
     * @param valueType the value type of this array type.
     */
    public ArrayType(ILocation loc, String[] typeParams, ASTType[] indexTypes, ASTType valueType) {
        super(loc);
        this.typeParams = typeParams;
        this.indexTypes = indexTypes;
        this.valueType = valueType;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ArrayType: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param boogieType the semantic type that is represented by this type.
     * @param typeParams the type params of this array type.
     * @param indexTypes the index types of this array type.
     * @param valueType the value type of this array type.
     */
    public ArrayType(ILocation loc, IBoogieType boogieType, String[] typeParams, ASTType[] indexTypes, ASTType valueType) {
        super(loc, boogieType);
        this.typeParams = typeParams;
        this.indexTypes = indexTypes;
        this.valueType = valueType;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ArrayType: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("ArrayType").append('[');
        if (typeParams == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < typeParams.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(typeParams[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (indexTypes == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < indexTypes.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(indexTypes[i1]);
            }
            sb.append(']');
        }
        sb.append(',').append(valueType);
        return sb.append(']').toString();
    }

    /**
     * Gets the type params of this array type.
     * @return the type params of this array type.
     */
    public String[] getTypeParams() {
        return typeParams;
    }

    /**
     * Gets the index types of this array type.
     * @return the index types of this array type.
     */
    public ASTType[] getIndexTypes() {
        return indexTypes;
    }

    /**
     * Gets the value type of this array type.
     * @return the value type of this array type.
     */
    public ASTType getValueType() {
        return valueType;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(indexTypes!=null){
            children.addAll(Arrays.asList(indexTypes));
        }
        children.add(valueType);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((ASTType)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(indexTypes!=null){
                for (ASTType elem : indexTypes) {
                    elem.accept(visitor);
                }
            }
            if(valueType!=null){
                valueType.accept(visitor);
            }
        }
    }

    public ASTType accept(GeneratedBoogieAstTransformer visitor) {
        ASTType node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<ASTType> tmpListnewindexTypes = new ArrayList<>();
        if(indexTypes != null){
            for(ASTType elem : indexTypes){
                ASTType newindexTypes = (ASTType)elem.accept(visitor);
                isChanged = isChanged || newindexTypes != elem;
                tmpListnewindexTypes.add(newindexTypes);
            }
        }
            ASTType newvalueType = null;
        if(valueType != null){
            newvalueType = (ASTType)valueType.accept(visitor);
        }
        if(isChanged || valueType != newvalueType){
            return new ArrayType(loc, boogieType, typeParams, tmpListnewindexTypes.toArray(new ASTType[0]), newvalueType);
        }
        return this;
    }
}
