/* ArrayAccessExpression -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a array access expression which is a special form of a expression.
 */
public class ArrayAccessExpression extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(ArrayAccessExpression.class);
    /**
     * The array of this array access expression.
     */
    Expression array;

    /**
     * The indices of this array access expression.
     */
    Expression[] indices;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param array the array of this array access expression.
     * @param indices the indices of this array access expression.
     */
    public ArrayAccessExpression(ILocation loc, Expression array, Expression[] indices) {
        super(loc);
        this.array = array;
        this.indices = indices;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ArrayAccessExpression: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param array the array of this array access expression.
     * @param indices the indices of this array access expression.
     */
    public ArrayAccessExpression(ILocation loc, IBoogieType type, Expression array, Expression[] indices) {
        super(loc, type);
        this.array = array;
        this.indices = indices;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ArrayAccessExpression: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("ArrayAccessExpression").append('[');
        sb.append(array);
        sb.append(',');
        if (indices == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < indices.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(indices[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the array of this array access expression.
     * @return the array of this array access expression.
     */
    public Expression getArray() {
        return array;
    }

    /**
     * Gets the indices of this array access expression.
     * @return the indices of this array access expression.
     */
    public Expression[] getIndices() {
        return indices;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(array);
        if(indices!=null){
            children.addAll(Arrays.asList(indices));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(array!=null){
                array.accept(visitor);
            }
            if(indices!=null){
                for (Expression elem : indices) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

            Expression newarray = null;
        if(array != null){
            newarray = (Expression)array.accept(visitor);
        }
        boolean isChanged=false;
            ArrayList<Expression> tmpListnewindices = new ArrayList<>();
        if(indices != null){
            for(Expression elem : indices){
                Expression newindices = (Expression)elem.accept(visitor);
                isChanged = isChanged || newindices != elem;
                tmpListnewindices.add(newindices);
            }
        }
        if(isChanged || array != newarray){
            return new ArrayAccessExpression(loc, type, newarray, tmpListnewindices.toArray(new Expression[0]));
        }
        return this;
    }
}
