/* ArrayLHS -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * An array left-hand-side represents an element of an array.
 */
public class ArrayLHS extends LeftHandSide {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(ArrayLHS.class);
    /**
     * A left-hand-side for the array whose element we represent.
     */
    LeftHandSide array;

    /**
     * The indices (can be more than one for multi-dimensional arrays).
     * The number of indices must match the type of the array.
     */
    Expression[] indices;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param array a left-hand-side for the array whose element we represent.
     * @param indices the indices (can be more than one for multi-dimensional arrays).
     */
    public ArrayLHS(ILocation loc, LeftHandSide array, Expression[] indices) {
        super(loc);
        this.array = array;
        this.indices = indices;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ArrayLHS: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of the object, i.
     * @param array a left-hand-side for the array whose element we represent.
     * @param indices the indices (can be more than one for multi-dimensional arrays).
     */
    public ArrayLHS(ILocation loc, IBoogieType type, LeftHandSide array, Expression[] indices) {
        super(loc, type);
        this.array = array;
        this.indices = indices;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ArrayLHS: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("ArrayLHS").append('[');
        sb.append(array);
        sb.append(',');
        if (indices == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < indices.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(indices[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets a left-hand-side for the array whose element we represent.
     * @return a left-hand-side for the array whose element we represent.
     */
    public LeftHandSide getArray() {
        return array;
    }

    /**
     * Gets the indices (can be more than one for multi-dimensional arrays).
     * The number of indices must match the type of the array.
     * @return the indices (can be more than one for multi-dimensional arrays).
     */
    public Expression[] getIndices() {
        return indices;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(array);
        if(indices!=null){
            children.addAll(Arrays.asList(indices));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((LeftHandSide)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(array!=null){
                array.accept(visitor);
            }
            if(indices!=null){
                for (Expression elem : indices) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public LeftHandSide accept(GeneratedBoogieAstTransformer visitor) {
        LeftHandSide node = visitor.transform(this);
        if(node != this){
            return node;
        }

            LeftHandSide newarray = null;
        if(array != null){
            newarray = (LeftHandSide)array.accept(visitor);
        }
        boolean isChanged=false;
            ArrayList<Expression> tmpListnewindices = new ArrayList<>();
        if(indices != null){
            for(Expression elem : indices){
                Expression newindices = (Expression)elem.accept(visitor);
                isChanged = isChanged || newindices != elem;
                tmpListnewindices.add(newindices);
            }
        }
        if(isChanged || array != newarray){
            return new ArrayLHS(loc, type, newarray, tmpListnewindices.toArray(new Expression[0]));
        }
        return this;
    }
}
