/* AssertStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Assert that a boolean formula holds. Program will terminate
 * with an error if it does not.
 */
public class AssertStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(AssertStatement.class);
    /**
     * The attributes of this assert statement.
     */
    NamedAttribute[] attributes;

    /**
     * The formula of this assert statement.
     */
    Expression formula;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param formula the formula of this assert statement.
     */
    public AssertStatement(ILocation loc, Expression formula) {
        super(loc);
        this.formula = formula;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid AssertStatement: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param attributes the attributes of this assert statement.
     * @param formula the formula of this assert statement.
     */
    public AssertStatement(ILocation loc, NamedAttribute[] attributes, Expression formula) {
        super(loc);
        this.attributes = attributes;
        this.formula = formula;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid AssertStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("AssertStatement").append('[');
        if (attributes == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < attributes.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(attributes[i1]);
            }
            sb.append(']');
        }
        sb.append(',').append(formula);
        return sb.append(']').toString();
    }

    /**
     * Gets the attributes of this assert statement.
     * @return the attributes of this assert statement.
     */
    public NamedAttribute[] getAttributes() {
        return attributes;
    }

    /**
     * Gets the formula of this assert statement.
     * @return the formula of this assert statement.
     */
    public Expression getFormula() {
        return formula;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(attributes!=null){
            children.addAll(Arrays.asList(attributes));
        }
        children.add(formula);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(attributes!=null){
                for (NamedAttribute elem : attributes) {
                    elem.accept(visitor);
                }
            }
            if(formula!=null){
                formula.accept(visitor);
            }
        }
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<NamedAttribute> tmpListnewattributes = new ArrayList<>();
        if(attributes != null){
            for(NamedAttribute elem : attributes){
                NamedAttribute newattributes = (NamedAttribute)elem.accept(visitor);
                isChanged = isChanged || newattributes != elem;
                tmpListnewattributes.add(newattributes);
            }
        }
            Expression newformula = null;
        if(formula != null){
            newformula = (Expression)formula.accept(visitor);
        }
        if(isChanged || formula != newformula){
            return new AssertStatement(loc, tmpListnewattributes.toArray(new NamedAttribute[0]), newformula);
        }
        return this;
    }
}
