/* AssignmentStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * An assignment operator. Multiple variables may be assigned
 * simultaneously, i.e., the right hand side are all evaluated
 * in the pre-state (and they do not have side-effects) and the
 * assignments are then all applied atomically.
 */
public class AssignmentStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(AssignmentStatement.class);
    /**
     * The lhs of this assignment statement.
     */
    LeftHandSide[] lhs;

    /**
     * The rhs of this assignment statement.
     */
    Expression[] rhs;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param lhs the lhs of this assignment statement.
     * @param rhs the rhs of this assignment statement.
     */
    public AssignmentStatement(ILocation loc, LeftHandSide[] lhs, Expression[] rhs) {
        super(loc);
        this.lhs = lhs;
        this.rhs = rhs;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid AssignmentStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("AssignmentStatement").append('[');
        if (lhs == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < lhs.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(lhs[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (rhs == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < rhs.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(rhs[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the lhs of this assignment statement.
     * @return the lhs of this assignment statement.
     */
    public LeftHandSide[] getLhs() {
        return lhs;
    }

    /**
     * Gets the rhs of this assignment statement.
     * @return the rhs of this assignment statement.
     */
    public Expression[] getRhs() {
        return rhs;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(lhs!=null){
            children.addAll(Arrays.asList(lhs));
        }
        if(rhs!=null){
            children.addAll(Arrays.asList(rhs));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(lhs!=null){
                for (LeftHandSide elem : lhs) {
                    elem.accept(visitor);
                }
            }
            if(rhs!=null){
                for (Expression elem : rhs) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<LeftHandSide> tmpListnewlhs = new ArrayList<>();
        if(lhs != null){
            for(LeftHandSide elem : lhs){
                LeftHandSide newlhs = (LeftHandSide)elem.accept(visitor);
                isChanged = isChanged || newlhs != elem;
                tmpListnewlhs.add(newlhs);
            }
        }
            ArrayList<Expression> tmpListnewrhs = new ArrayList<>();
        if(rhs != null){
            for(Expression elem : rhs){
                Expression newrhs = (Expression)elem.accept(visitor);
                isChanged = isChanged || newrhs != elem;
                tmpListnewrhs.add(newrhs);
            }
        }
        if(isChanged){
            return new AssignmentStatement(loc, tmpListnewlhs.toArray(new LeftHandSide[0]), tmpListnewrhs.toArray(new Expression[0]));
        }
        return this;
    }
}
