/* ASTType -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents an AST type.
 * This is different from BoogieType (in the type checker package), as
 * it is not unified and still
 * contains the names of the type parameters. You can think of this as
 * the syntactic type. For example, for defined types it just contains
 * the name, not the definition.
 */
public abstract class ASTType extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(ASTType.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * The semantic type that is represented by this type. This
     * is computed by the type checker.
     */
    IBoogieType boogieType;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     */
    public ASTType(ILocation loc) {
        super(loc);
        this.loc = loc;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ASTType: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param boogieType the semantic type that is represented by this type.
     */
    public ASTType(ILocation loc, IBoogieType boogieType) {
        super(loc);
        this.loc = loc;
        this.boogieType = boogieType;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ASTType: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("ASTType").append('[');
        sb.append(loc);
        sb.append(',').append(boogieType);
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Gets the semantic type that is represented by this type. This
     * is computed by the type checker.
     * @return the semantic type that is represented by this type.
     */
    public IBoogieType getBoogieType() {
        return boogieType;
    }

    /**
     * Sets the semantic type that is represented by this type. This
     * is computed by the type checker.
     * @param boogieType the semantic type that is represented by this type.
     */
    public void setBoogieType(IBoogieType boogieType) {
        this.boogieType = boogieType;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public abstract void accept(GeneratedBoogieAstVisitor visitor);

    public abstract ASTType accept(GeneratedBoogieAstTransformer visitor);
}
