/* Attribute -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Attributes are implementation-specific annotations that may appear
 * in all declarations and in quantifiers (for triggers).
 */
public abstract class Attribute extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Attribute.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     */
    public Attribute(ILocation loc) {
        super(loc);
        this.loc = loc;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Attribute: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Attribute").append('[');
        sb.append(loc);
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public abstract void accept(GeneratedBoogieAstVisitor visitor);

    public abstract Attribute accept(GeneratedBoogieAstTransformer visitor);
}
