/* Axiom -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * An axiom is a boolean expression that is assumed to be true and
 * can be used by the verifier to proof contracts.
 */
public class Axiom extends Declaration {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Axiom.class);
    /**
     * The formula of this axiom.
     */
    Expression formula;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param attributes the implementation specific attributes of this declaration.
     * @param formula the formula of this axiom.
     */
    public Axiom(ILocation loc, Attribute[] attributes, Expression formula) {
        super(loc, attributes);
        this.formula = formula;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Axiom: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Axiom").append('[');
        sb.append(formula);
        return sb.append(']').toString();
    }

    /**
     * Gets the formula of this axiom.
     * @return the formula of this axiom.
     */
    public Expression getFormula() {
        return formula;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(formula);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Declaration)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(formula!=null){
                formula.accept(visitor);
            }
            if(attributes!=null){
                for (Attribute elem : attributes) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Declaration accept(GeneratedBoogieAstTransformer visitor) {
        Declaration node = visitor.transform(this);
        if(node != this){
            return node;
        }

            Expression newformula = null;
        if(formula != null){
            newformula = (Expression)formula.accept(visitor);
        }
        boolean isChanged=false;
            ArrayList<Attribute> tmpListnewattributes = new ArrayList<>();
        if(attributes != null){
            for(Attribute elem : attributes){
                Attribute newattributes = (Attribute)elem.accept(visitor);
                isChanged = isChanged || newattributes != elem;
                tmpListnewattributes.add(newattributes);
            }
        }
        if(isChanged || formula != newformula){
            return new Axiom(loc, tmpListnewattributes.toArray(new Attribute[0]), newformula);
        }
        return this;
    }
}
