/* BinaryExpression -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a binary expression which is a special form of a expression.
 */
public class BinaryExpression extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(BinaryExpression.class);
    public enum Operator {
        LOGICIFF, LOGICIMPLIES, LOGICAND, LOGICOR, COMPLT, COMPGT, COMPLEQ, 
        COMPGEQ, COMPEQ, COMPNEQ, COMPPO, BITVECCONCAT, ARITHPLUS, ARITHMINUS, 
        ARITHMUL, ARITHDIV, ARITHMOD
    }

    /**
     * The operator of this binary expression.
     */
    Operator operator;

    /**
     * The left of this binary expression.
     */
    Expression left;

    /**
     * The right of this binary expression.
     */
    Expression right;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param operator the operator of this binary expression.
     * @param left the left of this binary expression.
     * @param right the right of this binary expression.
     */
    public BinaryExpression(ILocation loc, Operator operator, Expression left, Expression right) {
        super(loc);
        this.operator = operator;
        this.left = left;
        this.right = right;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid BinaryExpression: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param operator the operator of this binary expression.
     * @param left the left of this binary expression.
     * @param right the right of this binary expression.
     */
    public BinaryExpression(ILocation loc, IBoogieType type, Operator operator, Expression left, Expression right) {
        super(loc, type);
        this.operator = operator;
        this.left = left;
        this.right = right;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid BinaryExpression: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("BinaryExpression").append('[');
        sb.append(operator);
        sb.append(',').append(left);
        sb.append(',').append(right);
        return sb.append(']').toString();
    }

    /**
     * Gets the operator of this binary expression.
     * @return the operator of this binary expression.
     */
    public Operator getOperator() {
        return operator;
    }

    /**
     * Gets the left of this binary expression.
     * @return the left of this binary expression.
     */
    public Expression getLeft() {
        return left;
    }

    /**
     * Gets the right of this binary expression.
     * @return the right of this binary expression.
     */
    public Expression getRight() {
        return right;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(left);
        children.add(right);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(left!=null){
                left.accept(visitor);
            }
            if(right!=null){
                right.accept(visitor);
            }
        }
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

            Expression newleft = null;
        if(left != null){
            newleft = (Expression)left.accept(visitor);
        }
            Expression newright = null;
        if(right != null){
            newright = (Expression)right.accept(visitor);
        }
        if(left != newleft || right != newright){
            return new BinaryExpression(loc, type, operator, newleft, newright);
        }
        return this;
    }
}
