/* BitVectorAccessExpression -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a bit vector access expression which is a special form of a expression.
 */
public class BitVectorAccessExpression extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(BitVectorAccessExpression.class);
    /**
     * The sub expression representing the bit-vector.
     */
    Expression bitvec;

    /**
     * The end index of this bit-vector access.
     */
    int end;

    /**
     * The start index of this bit-vector access.
     */
    int start;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param bitvec the sub expression representing the bit-vector.
     * @param end the end index of this bit-vector access.
     * @param start the start index of this bit-vector access.
     */
    public BitVectorAccessExpression(ILocation loc, Expression bitvec, int end, int start) {
        super(loc);
        this.bitvec = bitvec;
        this.end = end;
        this.start = start;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid BitVectorAccessExpression: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param bitvec the sub expression representing the bit-vector.
     * @param end the end index of this bit-vector access.
     * @param start the start index of this bit-vector access.
     */
    public BitVectorAccessExpression(ILocation loc, IBoogieType type, Expression bitvec, int end, int start) {
        super(loc, type);
        this.bitvec = bitvec;
        this.end = end;
        this.start = start;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid BitVectorAccessExpression: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("BitVectorAccessExpression").append('[');
        sb.append(bitvec);
        sb.append(',').append(end);
        sb.append(',').append(start);
        return sb.append(']').toString();
    }

    /**
     * Gets the sub expression representing the bit-vector.
     * @return the sub expression representing the bit-vector.
     */
    public Expression getBitvec() {
        return bitvec;
    }

    /**
     * Gets the end index of this bit-vector access.
     * @return the end index of this bit-vector access.
     */
    public int getEnd() {
        return end;
    }

    /**
     * Gets the start index of this bit-vector access.
     * @return the start index of this bit-vector access.
     */
    public int getStart() {
        return start;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(bitvec);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(bitvec!=null){
                bitvec.accept(visitor);
            }
        }
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

            Expression newbitvec = null;
        if(bitvec != null){
            newbitvec = (Expression)bitvec.accept(visitor);
        }
        if(bitvec != newbitvec){
            return new BitVectorAccessExpression(loc, type, newbitvec, end, start);
        }
        return this;
    }
}
