/* Body -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a body.
 */
public class Body extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Body.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * The local vars of this body.
     */
    VariableDeclaration[] localVars;

    /**
     * The block of this body.
     */
    Statement[] block;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param localVars the local vars of this body.
     * @param block the block of this body.
     */
    public Body(ILocation loc, VariableDeclaration[] localVars, Statement[] block) {
        super(loc);
        this.loc = loc;
        this.localVars = localVars;
        this.block = block;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Body: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Body").append('[');
        sb.append(loc);
        sb.append(',');
        if (localVars == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < localVars.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(localVars[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (block == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < block.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(block[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Gets the local vars of this body.
     * @return the local vars of this body.
     */
    public VariableDeclaration[] getLocalVars() {
        return localVars;
    }

    /**
     * Sets the local vars of this body.
     * @param localVars the local vars of this body.
     */
    public void setLocalVars(VariableDeclaration[] localVars) {
        this.localVars = localVars;
    }

    /**
     * Gets the block of this body.
     * @return the block of this body.
     */
    public Statement[] getBlock() {
        return block;
    }

    /**
     * Sets the block of this body.
     * @param block the block of this body.
     */
    public void setBlock(Statement[] block) {
        this.block = block;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(localVars!=null){
            children.addAll(Arrays.asList(localVars));
        }
        if(block!=null){
            children.addAll(Arrays.asList(block));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit(this)) {
            if(localVars!=null){
                for (VariableDeclaration elem : localVars) {
                    elem.accept(visitor);
                }
            }
            if(block!=null){
                for (Statement elem : block) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Body accept(GeneratedBoogieAstTransformer visitor) {
        Body node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<VariableDeclaration> tmpListnewlocalVars = new ArrayList<>();
        if(localVars != null){
            for(VariableDeclaration elem : localVars){
                VariableDeclaration newlocalVars = (VariableDeclaration)elem.accept(visitor);
                isChanged = isChanged || newlocalVars != elem;
                tmpListnewlocalVars.add(newlocalVars);
            }
        }
            ArrayList<Statement> tmpListnewblock = new ArrayList<>();
        if(block != null){
            for(Statement elem : block){
                Statement newblock = (Statement)elem.accept(visitor);
                isChanged = isChanged || newblock != elem;
                tmpListnewblock.add(newblock);
            }
        }
        if(isChanged){
            return new Body(loc, tmpListnewlocalVars.toArray(new VariableDeclaration[0]), tmpListnewblock.toArray(new Statement[0]));
        }
        return this;
    }
}
