/* BooleanLiteral -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a boolean literal which is a special form of a expression.
 */
public class BooleanLiteral extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(BooleanLiteral.class);
    /**
     * The value of this boolean literal.
     */
    boolean value;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param value the value of this boolean literal.
     */
    public BooleanLiteral(ILocation loc, boolean value) {
        super(loc);
        this.value = value;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid BooleanLiteral: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param value the value of this boolean literal.
     */
    public BooleanLiteral(ILocation loc, IBoogieType type, boolean value) {
        super(loc, type);
        this.value = value;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid BooleanLiteral: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("BooleanLiteral").append('[');
        sb.append(value);
        return sb.append(']').toString();
    }

    /**
     * Checks the value of this boolean literal.
     * @return the value of this boolean literal.
     */
    public boolean getValue() {
        return value;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
