/* BreakStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * The break statement is used to jump out of a while loop.
 */
public class BreakStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(BreakStatement.class);
    /**
     * The label of the while loop.
     * If null breaks the immediate surrounding while loop. Otherwise
     * it must be a label that immediately precedes a surrounding
     * while-loop (there may only be other labels between the label and
     * the while-loop). Note that this does not jump to the label but
     * to the statement after the while loop.
     */
    String label;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     */
    public BreakStatement(ILocation loc) {
        super(loc);
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid BreakStatement: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param label the label of the while loop.
     */
    public BreakStatement(ILocation loc, String label) {
        super(loc);
        this.label = label;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid BreakStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("BreakStatement").append('[');
        sb.append(label);
        return sb.append(']').toString();
    }

    /**
     * Gets the label of the while loop.
     * If null breaks the immediate surrounding while loop. Otherwise
     * it must be a label that immediately precedes a surrounding
     * while-loop (there may only be other labels between the label and
     * the while-loop). Note that this does not jump to the label but
     * to the statement after the while loop.
     * @return the label of the while loop.
     */
    public String getLabel() {
        return label;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
