/* CallStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * A procedure call. This is always combined with an assignment.
 * The left hand side must be variables, arrays are not allowed.
 * The arguments are evaluated before the procedure call and then
 * the side-effects of the procedure call occur.
 */
public class CallStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(CallStatement.class);
    /**
     * True if this is a forall procedure call.
     * In Boogie there are special forall procedure calls. See the
     * Boogie documentation for more details. This is usually false.
     */
    boolean isForall;

    /**
     * The variables where the return values are written to.
     */
    VariableLHS[] lhs;

    /**
     * The name of the procedure.
     */
    String methodName;

    /**
     * The arguments. This must contain the same number of expressions
     * as there are input parameters to the procedure.
     * If {@link #isForall()} is true, the argument can be a wildcard
     * and the procedure is &ldquo;called&rdquo; for all possible values.
     * This is used for lemma procedures which should not have any
     * side effects.
     */
    Expression[] arguments;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param isForall true if this is a forall procedure call.
     * @param lhs the variables where the return values are written to.
     * @param methodName the name of the procedure.
     * @param arguments the arguments.
     */
    public CallStatement(ILocation loc, boolean isForall, VariableLHS[] lhs, String methodName, Expression[] arguments) {
        super(loc);
        this.isForall = isForall;
        this.lhs = lhs;
        this.methodName = methodName;
        this.arguments = arguments;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid CallStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("CallStatement").append('[');
        sb.append(isForall);
        sb.append(',');
        if (lhs == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < lhs.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(lhs[i1]);
            }
            sb.append(']');
        }
        sb.append(',').append(methodName);
        sb.append(',');
        if (arguments == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < arguments.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(arguments[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Checks if this is a forall procedure call.
     * In Boogie there are special forall procedure calls. See the
     * Boogie documentation for more details. This is usually false.
     * @return true if this is a forall procedure call.
     */
    public boolean isForall() {
        return isForall;
    }

    /**
     * Gets the variables where the return values are written to.
     * @return the variables where the return values are written to.
     */
    public VariableLHS[] getLhs() {
        return lhs;
    }

    /**
     * Gets the name of the procedure.
     * @return the name of the procedure.
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * Gets the arguments. This must contain the same number of expressions
     * as there are input parameters to the procedure.
     * If {@link #isForall()} is true, the argument can be a wildcard
     * and the procedure is &ldquo;called&rdquo; for all possible values.
     * This is used for lemma procedures which should not have any
     * side effects.
     * @return the arguments.
     */
    public Expression[] getArguments() {
        return arguments;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(lhs!=null){
            children.addAll(Arrays.asList(lhs));
        }
        if(arguments!=null){
            children.addAll(Arrays.asList(arguments));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(lhs!=null){
                for (VariableLHS elem : lhs) {
                    elem.accept(visitor);
                }
            }
            if(arguments!=null){
                for (Expression elem : arguments) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<VariableLHS> tmpListnewlhs = new ArrayList<>();
        if(lhs != null){
            for(VariableLHS elem : lhs){
                VariableLHS newlhs = (VariableLHS)elem.accept(visitor);
                isChanged = isChanged || newlhs != elem;
                tmpListnewlhs.add(newlhs);
            }
        }
            ArrayList<Expression> tmpListnewarguments = new ArrayList<>();
        if(arguments != null){
            for(Expression elem : arguments){
                Expression newarguments = (Expression)elem.accept(visitor);
                isChanged = isChanged || newarguments != elem;
                tmpListnewarguments.add(newarguments);
            }
        }
        if(isChanged){
            return new CallStatement(loc, isForall, tmpListnewlhs.toArray(new VariableLHS[0]), methodName, tmpListnewarguments.toArray(new Expression[0]));
        }
        return this;
    }
}
