/* ConstDeclaration -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a const declaration which is a special form of a declaration.
 */
public class ConstDeclaration extends Declaration {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(ConstDeclaration.class);
    /**
     * True iff the constants are unique. A unique constant
     * is disjoint from all other unique constants.
     */
    boolean isUnique;

    /**
     * The constants declared, together with their type.
     */
    VarList varList;

    /**
     * The parent info. This lists all the immediate parents p,
     * such that this &lt;: p. If this is null, there is nothing
     * known about the parents, if this is empty, there are no
     * parents at all.
     */
    ParentEdge[] parentInfo;

    /**
     * True iff this object is only an immediate parent
     * of those constants, that list this object in the parentInfo.
     */
    boolean isComplete;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param attributes the implementation specific attributes of this declaration.
     * @param isUnique true iff the constants are unique.
     * @param varList the constants declared, together with their type.
     * @param parentInfo the parent info.
     * @param isComplete true iff this object is only an immediate parent
     * of those constants, that list this object in the parentInfo.
     */
    public ConstDeclaration(ILocation loc, Attribute[] attributes, boolean isUnique, VarList varList, ParentEdge[] parentInfo, boolean isComplete) {
        super(loc, attributes);
        this.isUnique = isUnique;
        this.varList = varList;
        this.parentInfo = parentInfo;
        this.isComplete = isComplete;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ConstDeclaration: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("ConstDeclaration").append('[');
        sb.append(isUnique);
        sb.append(',').append(varList);
        sb.append(',');
        if (parentInfo == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < parentInfo.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(parentInfo[i1]);
            }
            sb.append(']');
        }
        sb.append(',').append(isComplete);
        return sb.append(']').toString();
    }

    /**
     * Checks iff the constants are unique. A unique constant
     * is disjoint from all other unique constants.
     * @return true iff the constants are unique.
     */
    public boolean isUnique() {
        return isUnique;
    }

    /**
     * Gets the constants declared, together with their type.
     * @return the constants declared, together with their type.
     */
    public VarList getVarList() {
        return varList;
    }

    /**
     * Gets the parent info. This lists all the immediate parents p,
     * such that this &lt;: p. If this is null, there is nothing
     * known about the parents, if this is empty, there are no
     * parents at all.
     * @return the parent info.
     */
    public ParentEdge[] getParentInfo() {
        return parentInfo;
    }

    /**
     * Checks iff this object is only an immediate parent
     * of those constants, that list this object in the parentInfo.
     * @return true iff this object is only an immediate parent
     * of those constants, that list this object in the parentInfo.
     */
    public boolean isComplete() {
        return isComplete;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(varList);
        if(parentInfo!=null){
            children.addAll(Arrays.asList(parentInfo));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Declaration)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(varList!=null){
                varList.accept(visitor);
            }
            if(parentInfo!=null){
                for (ParentEdge elem : parentInfo) {
                    elem.accept(visitor);
                }
            }
            if(attributes!=null){
                for (Attribute elem : attributes) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Declaration accept(GeneratedBoogieAstTransformer visitor) {
        Declaration node = visitor.transform(this);
        if(node != this){
            return node;
        }

            VarList newvarList = null;
        if(varList != null){
            newvarList = (VarList)varList.accept(visitor);
        }
        boolean isChanged=false;
            ArrayList<ParentEdge> tmpListnewparentInfo = new ArrayList<>();
        if(parentInfo != null){
            for(ParentEdge elem : parentInfo){
                ParentEdge newparentInfo = (ParentEdge)elem.accept(visitor);
                isChanged = isChanged || newparentInfo != elem;
                tmpListnewparentInfo.add(newparentInfo);
            }
        }
            ArrayList<Attribute> tmpListnewattributes = new ArrayList<>();
        if(attributes != null){
            for(Attribute elem : attributes){
                Attribute newattributes = (Attribute)elem.accept(visitor);
                isChanged = isChanged || newattributes != elem;
                tmpListnewattributes.add(newattributes);
            }
        }
        if(isChanged || varList != newvarList){
            return new ConstDeclaration(loc, tmpListnewattributes.toArray(new Attribute[0]), isUnique, newvarList, tmpListnewparentInfo.toArray(new ParentEdge[0]), isComplete);
        }
        return this;
    }
}
