/* Declaration -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Every declaration is one of
 * {@link TypeDeclaration}, {@link ConstDeclaration},
 * {@link Axiom}, {@link FunctionDeclaration}, {@link VariableDeclaration},
 * or {@link Procedure}.
 * A declaration can have attributes, which are all implementation specific.
 */
public abstract class Declaration extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Declaration.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * The implementation specific attributes of this declaration.
     * Usually this is the empty array.
     */
    Attribute[] attributes;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param attributes the implementation specific attributes of this declaration.
     */
    public Declaration(ILocation loc, Attribute[] attributes) {
        super(loc);
        this.loc = loc;
        this.attributes = attributes;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Declaration: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Declaration").append('[');
        sb.append(loc);
        sb.append(',');
        if (attributes == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < attributes.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(attributes[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Gets the implementation specific attributes of this declaration.
     * Usually this is the empty array.
     * @return the implementation specific attributes of this declaration.
     */
    public Attribute[] getAttributes() {
        return attributes;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(attributes!=null){
            children.addAll(Arrays.asList(attributes));
        }
        return children;
    }

    public abstract void accept(GeneratedBoogieAstVisitor visitor);

    public abstract Declaration accept(GeneratedBoogieAstTransformer visitor);
}
