/* EnsuresSpecification -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a ensures specification which is a special form of a specification.
 */
public class EnsuresSpecification extends Specification {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(EnsuresSpecification.class);
    /**
     * The formula of this ensures specification.
     */
    Expression formula;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param isFree true iff this specification is free.
     * @param formula the formula of this ensures specification.
     */
    public EnsuresSpecification(ILocation loc, boolean isFree, Expression formula) {
        super(loc, isFree);
        this.formula = formula;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid EnsuresSpecification: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("EnsuresSpecification").append('[');
        sb.append(formula);
        return sb.append(']').toString();
    }

    /**
     * Gets the formula of this ensures specification.
     * @return the formula of this ensures specification.
     */
    public Expression getFormula() {
        return formula;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(formula);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Specification)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(formula!=null){
                formula.accept(visitor);
            }
        }
    }

    public Specification accept(GeneratedBoogieAstTransformer visitor) {
        Specification node = visitor.transform(this);
        if(node != this){
            return node;
        }

            Expression newformula = null;
        if(formula != null){
            newformula = (Expression)formula.accept(visitor);
        }
        if(formula != newformula){
            return new EnsuresSpecification(loc, isFree, newformula);
        }
        return this;
    }
}
