/* Expression -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * This node represents an expression.
 * This base class is almost empty, the sub classes contain the possible
 * expressions.
 */
public abstract class Expression extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Expression.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * The type of this expression. This is set by the type-checker.
     */
    IBoogieType type;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     */
    public Expression(ILocation loc) {
        super(loc);
        this.loc = loc;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Expression: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     */
    public Expression(ILocation loc, IBoogieType type) {
        super(loc);
        this.loc = loc;
        this.type = type;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Expression: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Expression").append('[');
        sb.append(loc);
        sb.append(',').append(type);
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Gets the type of this expression. This is set by the type-checker.
     * @return the type of this expression.
     */
    public IBoogieType getType() {
        return type;
    }

    /**
     * Sets the type of this expression. This is set by the type-checker.
     * @param type the type of this expression.
     */
    public void setType(IBoogieType type) {
        this.type = type;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public abstract void accept(GeneratedBoogieAstVisitor visitor);

    public abstract Expression accept(GeneratedBoogieAstTransformer visitor);
}
