/* ForkStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * A asynchrone procedure call.
 * The arguments are evaluated before the procedure call and then
 * the side-effects of the procedure call occur.
 */
public class ForkStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(ForkStatement.class);
    /**
     * An id or list of id's referencing that fork statement out of multiple ones.
     */
    Expression[] threadID;

    /**
     * The name of the procedure.
     */
    String procedureName;

    /**
     * The arguments. This must contain the same number of expressions
     * as there are input parameters to the procedure.
     * If {@link #isForall()} is true, the argument can be a wildcard
     * and the procedure is &ldquo;called&rdquo; for all possible values.
     * This is used for lemma procedures which should not have any
     * side effects.
     */
    Expression[] arguments;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param threadID an id or list of id's referencing that fork statement out of multiple ones.
     * @param procedureName the name of the procedure.
     * @param arguments the arguments.
     */
    public ForkStatement(ILocation loc, Expression[] threadID, String procedureName, Expression[] arguments) {
        super(loc);
        this.threadID = threadID;
        this.procedureName = procedureName;
        this.arguments = arguments;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ForkStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("ForkStatement").append('[');
        if (threadID == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < threadID.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(threadID[i1]);
            }
            sb.append(']');
        }
        sb.append(',').append(procedureName);
        sb.append(',');
        if (arguments == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < arguments.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(arguments[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets an id or list of id's referencing that fork statement out of multiple ones.
     * @return an id or list of id's referencing that fork statement out of multiple ones.
     */
    public Expression[] getThreadID() {
        return threadID;
    }

    /**
     * Gets the name of the procedure.
     * @return the name of the procedure.
     */
    public String getProcedureName() {
        return procedureName;
    }

    /**
     * Gets the arguments. This must contain the same number of expressions
     * as there are input parameters to the procedure.
     * If {@link #isForall()} is true, the argument can be a wildcard
     * and the procedure is &ldquo;called&rdquo; for all possible values.
     * This is used for lemma procedures which should not have any
     * side effects.
     * @return the arguments.
     */
    public Expression[] getArguments() {
        return arguments;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(threadID!=null){
            children.addAll(Arrays.asList(threadID));
        }
        if(arguments!=null){
            children.addAll(Arrays.asList(arguments));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(threadID!=null){
                for (Expression elem : threadID) {
                    elem.accept(visitor);
                }
            }
            if(arguments!=null){
                for (Expression elem : arguments) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<Expression> tmpListnewthreadID = new ArrayList<>();
        if(threadID != null){
            for(Expression elem : threadID){
                Expression newthreadID = (Expression)elem.accept(visitor);
                isChanged = isChanged || newthreadID != elem;
                tmpListnewthreadID.add(newthreadID);
            }
        }
            ArrayList<Expression> tmpListnewarguments = new ArrayList<>();
        if(arguments != null){
            for(Expression elem : arguments){
                Expression newarguments = (Expression)elem.accept(visitor);
                isChanged = isChanged || newarguments != elem;
                tmpListnewarguments.add(newarguments);
            }
        }
        if(isChanged){
            return new ForkStatement(loc, tmpListnewthreadID.toArray(new Expression[0]), procedureName, tmpListnewarguments.toArray(new Expression[0]));
        }
        return this;
    }
}
