/* FunctionApplication -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a function application of a (mathematical) function
 * declared by a {@see FunctionDeclaration}.
 */
public class FunctionApplication extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(FunctionApplication.class);
    /**
     * The identifier of this function application.
     */
    String identifier;

    /**
     * The function arguments. The number and types must match the
     * input parameters declared for these functions.
     */
    Expression[] arguments;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param identifier the identifier of this function application.
     * @param arguments the function arguments.
     */
    public FunctionApplication(ILocation loc, String identifier, Expression[] arguments) {
        super(loc);
        this.identifier = identifier;
        this.arguments = arguments;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid FunctionApplication: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param identifier the identifier of this function application.
     * @param arguments the function arguments.
     */
    public FunctionApplication(ILocation loc, IBoogieType type, String identifier, Expression[] arguments) {
        super(loc, type);
        this.identifier = identifier;
        this.arguments = arguments;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid FunctionApplication: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("FunctionApplication").append('[');
        sb.append(identifier);
        sb.append(',');
        if (arguments == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < arguments.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(arguments[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the identifier of this function application.
     * @return the identifier of this function application.
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Gets the function arguments. The number and types must match the
     * input parameters declared for these functions.
     * @return the function arguments.
     */
    public Expression[] getArguments() {
        return arguments;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(arguments!=null){
            children.addAll(Arrays.asList(arguments));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(arguments!=null){
                for (Expression elem : arguments) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<Expression> tmpListnewarguments = new ArrayList<>();
        if(arguments != null){
            for(Expression elem : arguments){
                Expression newarguments = (Expression)elem.accept(visitor);
                isChanged = isChanged || newarguments != elem;
                tmpListnewarguments.add(newarguments);
            }
        }
        if(isChanged){
            return new FunctionApplication(loc, type, identifier, tmpListnewarguments.toArray(new Expression[0]));
        }
        return this;
    }
}
