/* FunctionDeclaration -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * A function declaration declares (<code>getBody() == null</code>)
 * or defines a mathematical function. A function cannot have
 * side-effects. If it is only declared, then it is an uninterpreted
 * function and its meaning can be given by axioms. Otherwise
 * the function definition basically defines an abbreviation and
 * <code>getBody()</code> contains the expression for which the
 * function stands for.
 */
public class FunctionDeclaration extends Declaration {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(FunctionDeclaration.class);
    /**
     * The name of the function.
     */
    String identifier;

    /**
     * The type parameters of the function. This is used for
     * polymorphic functions, that take input of an arbitrary type.
     * For non-polymorphic functions the array is empty.
     */
    String[] typeParams;

    /**
     * The input parameters of the function.
     */
    VarList[] inParams;

    /**
     * The output parameter of the function. Note that the VarList
     * must only contain a single identifier.
     */
    VarList outParam;

    /**
     * The definition of the function. This is <code>null</code> for
     * uninterpreted function. Otherwise it is an expression with the
     * same type as the output paramter. It may contain identifier
     * expressions referencing the input parameters.
     */
    Expression body;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param attributes the implementation specific attributes of this declaration.
     * @param identifier the name of the function.
     * @param typeParams the type parameters of the function.
     * @param inParams the input parameters of the function.
     * @param outParam the output parameter of the function.
     */
    public FunctionDeclaration(ILocation loc, Attribute[] attributes, String identifier, String[] typeParams, VarList[] inParams, VarList outParam) {
        super(loc, attributes);
        this.identifier = identifier;
        this.typeParams = typeParams;
        this.inParams = inParams;
        this.outParam = outParam;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid FunctionDeclaration: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param attributes the implementation specific attributes of this declaration.
     * @param identifier the name of the function.
     * @param typeParams the type parameters of the function.
     * @param inParams the input parameters of the function.
     * @param outParam the output parameter of the function.
     * @param body the definition of the function.
     */
    public FunctionDeclaration(ILocation loc, Attribute[] attributes, String identifier, String[] typeParams, VarList[] inParams, VarList outParam, Expression body) {
        super(loc, attributes);
        this.identifier = identifier;
        this.typeParams = typeParams;
        this.inParams = inParams;
        this.outParam = outParam;
        this.body = body;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid FunctionDeclaration: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("FunctionDeclaration").append('[');
        sb.append(identifier);
        sb.append(',');
        if (typeParams == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < typeParams.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(typeParams[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (inParams == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < inParams.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(inParams[i1]);
            }
            sb.append(']');
        }
        sb.append(',').append(outParam);
        sb.append(',').append(body);
        return sb.append(']').toString();
    }

    /**
     * Gets the name of the function.
     * @return the name of the function.
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Gets the type parameters of the function. This is used for
     * polymorphic functions, that take input of an arbitrary type.
     * For non-polymorphic functions the array is empty.
     * @return the type parameters of the function.
     */
    public String[] getTypeParams() {
        return typeParams;
    }

    /**
     * Gets the input parameters of the function.
     * @return the input parameters of the function.
     */
    public VarList[] getInParams() {
        return inParams;
    }

    /**
     * Gets the output parameter of the function. Note that the VarList
     * must only contain a single identifier.
     * @return the output parameter of the function.
     */
    public VarList getOutParam() {
        return outParam;
    }

    /**
     * Gets the definition of the function. This is <code>null</code> for
     * uninterpreted function. Otherwise it is an expression with the
     * same type as the output paramter. It may contain identifier
     * expressions referencing the input parameters.
     * @return the definition of the function.
     */
    public Expression getBody() {
        return body;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(inParams!=null){
            children.addAll(Arrays.asList(inParams));
        }
        children.add(outParam);
        children.add(body);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Declaration)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(inParams!=null){
                for (VarList elem : inParams) {
                    elem.accept(visitor);
                }
            }
            if(outParam!=null){
                outParam.accept(visitor);
            }
            if(body!=null){
                body.accept(visitor);
            }
            if(attributes!=null){
                for (Attribute elem : attributes) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Declaration accept(GeneratedBoogieAstTransformer visitor) {
        Declaration node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<VarList> tmpListnewinParams = new ArrayList<>();
        if(inParams != null){
            for(VarList elem : inParams){
                VarList newinParams = (VarList)elem.accept(visitor);
                isChanged = isChanged || newinParams != elem;
                tmpListnewinParams.add(newinParams);
            }
        }
            VarList newoutParam = null;
        if(outParam != null){
            newoutParam = (VarList)outParam.accept(visitor);
        }
            Expression newbody = null;
        if(body != null){
            newbody = (Expression)body.accept(visitor);
        }
            ArrayList<Attribute> tmpListnewattributes = new ArrayList<>();
        if(attributes != null){
            for(Attribute elem : attributes){
                Attribute newattributes = (Attribute)elem.accept(visitor);
                isChanged = isChanged || newattributes != elem;
                tmpListnewattributes.add(newattributes);
            }
        }
        if(isChanged || outParam != newoutParam || body != newbody){
            return new FunctionDeclaration(loc, tmpListnewattributes.toArray(new Attribute[0]), identifier, typeParams, tmpListnewinParams.toArray(new VarList[0]), newoutParam, newbody);
        }
        return this;
    }
}
