/* GeneratedBoogieAstVisitor -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * 
 */
public class GeneratedBoogieAstVisitor {
    /**
     * The constructor taking initial values.
     */
    public GeneratedBoogieAstVisitor() {
        super();
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        return "GeneratedBoogieAstVisitor";
    }

    public boolean visit(NamedAttribute node) {
        return true;
    }

    public boolean visit(StructType node) {
        return true;
    }

    public boolean visit(LeftHandSide node) {
        return true;
    }

    public boolean visit(FunctionApplication node) {
        return true;
    }

    public boolean visit(Label node) {
        return true;
    }

    public boolean visit(Unit node) {
        return true;
    }

    public boolean visit(VarList node) {
        return true;
    }

    public boolean visit(ArrayType node) {
        return true;
    }

    public boolean visit(IfStatement node) {
        return true;
    }

    public boolean visit(ParentEdge node) {
        return true;
    }

    public boolean visit(Trigger node) {
        return true;
    }

    public boolean visit(BinaryExpression node) {
        return true;
    }

    public boolean visit(AssignmentStatement node) {
        return true;
    }

    public boolean visit(LoopInvariantSpecification node) {
        return true;
    }

    public boolean visit(ReturnStatement node) {
        return true;
    }

    public boolean visit(Procedure node) {
        return true;
    }

    public boolean visit(PrimitiveType node) {
        return true;
    }

    public boolean visit(WildcardExpression node) {
        return true;
    }

    public boolean visit(Axiom node) {
        return true;
    }

    public boolean visit(IntegerLiteral node) {
        return true;
    }

    public boolean visit(EnsuresSpecification node) {
        return true;
    }

    public boolean visit(StructAccessExpression node) {
        return true;
    }

    public boolean visit(ForkStatement node) {
        return true;
    }

    public boolean visit(CallStatement node) {
        return true;
    }

    public boolean visit(JoinStatement node) {
        return true;
    }

    public boolean visit(VariableLHS node) {
        return true;
    }

    public boolean visit(Project node) {
        return true;
    }

    public boolean visit(ArrayStoreExpression node) {
        return true;
    }

    public boolean visit(StringLiteral node) {
        return true;
    }

    public boolean visit(ArrayLHS node) {
        return true;
    }

    public boolean visit(AssertStatement node) {
        return true;
    }

    public boolean visit(ModifiesSpecification node) {
        return true;
    }

    public boolean visit(RequiresSpecification node) {
        return true;
    }

    public boolean visit(Attribute node) {
        return true;
    }

    public boolean visit(NamedType node) {
        return true;
    }

    public boolean visit(BooleanLiteral node) {
        return true;
    }

    public boolean visit(UnaryExpression node) {
        return true;
    }

    public boolean visit(QuantifierExpression node) {
        return true;
    }

    public boolean visit(WhileStatement node) {
        return true;
    }

    public boolean visit(StructLHS node) {
        return true;
    }

    public boolean visit(ConstDeclaration node) {
        return true;
    }

    public boolean visit(FunctionDeclaration node) {
        return true;
    }

    public boolean visit(RealLiteral node) {
        return true;
    }

    public boolean visit(GotoStatement node) {
        return true;
    }

    public boolean visit(VariableDeclaration node) {
        return true;
    }

    public boolean visit(Declaration node) {
        return true;
    }

    public boolean visit(Body node) {
        return true;
    }

    public boolean visit(StructConstructor node) {
        return true;
    }

    public boolean visit(AtomicStatement node) {
        return true;
    }

    public boolean visit(ASTType node) {
        return true;
    }

    public boolean visit(BitvecLiteral node) {
        return true;
    }

    public boolean visit(AssumeStatement node) {
        return true;
    }

    public boolean visit(Statement node) {
        return true;
    }

    public boolean visit(Specification node) {
        return true;
    }

    public boolean visit(IfThenElseExpression node) {
        return true;
    }

    public boolean visit(IdentifierExpression node) {
        return true;
    }

    public boolean visit(BreakStatement node) {
        return true;
    }

    public boolean visit(Expression node) {
        return true;
    }

    public boolean visit(BitVectorAccessExpression node) {
        return true;
    }

    public boolean visit(TypeDeclaration node) {
        return true;
    }

    public boolean visit(ArrayAccessExpression node) {
        return true;
    }

    public boolean visit(HavocStatement node) {
        return true;
    }
}
