/* GeneratedBoogieAstTransformer -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * 
 */
public class GeneratedBoogieAstTransformer {
    /**
     * The constructor taking initial values.
     */
    public GeneratedBoogieAstTransformer() {
        super();
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        return "GeneratedBoogieAstTransformer";
    }

    public Attribute transform(NamedAttribute node) {
        return node;
    }

    public ASTType transform(StructType node) {
        return node;
    }

    public LeftHandSide transform(LeftHandSide node) {
        return node;
    }

    public Expression transform(FunctionApplication node) {
        return node;
    }

    public Statement transform(Label node) {
        return node;
    }

    public Unit transform(Unit node) {
        return node;
    }

    public VarList transform(VarList node) {
        return node;
    }

    public ASTType transform(ArrayType node) {
        return node;
    }

    public Statement transform(IfStatement node) {
        return node;
    }

    public ParentEdge transform(ParentEdge node) {
        return node;
    }

    public Attribute transform(Trigger node) {
        return node;
    }

    public Expression transform(BinaryExpression node) {
        return node;
    }

    public Statement transform(AssignmentStatement node) {
        return node;
    }

    public Specification transform(LoopInvariantSpecification node) {
        return node;
    }

    public Statement transform(ReturnStatement node) {
        return node;
    }

    public Declaration transform(Procedure node) {
        return node;
    }

    public ASTType transform(PrimitiveType node) {
        return node;
    }

    public Expression transform(WildcardExpression node) {
        return node;
    }

    public Declaration transform(Axiom node) {
        return node;
    }

    public Expression transform(IntegerLiteral node) {
        return node;
    }

    public Specification transform(EnsuresSpecification node) {
        return node;
    }

    public Expression transform(StructAccessExpression node) {
        return node;
    }

    public Statement transform(ForkStatement node) {
        return node;
    }

    public Statement transform(CallStatement node) {
        return node;
    }

    public Statement transform(JoinStatement node) {
        return node;
    }

    public LeftHandSide transform(VariableLHS node) {
        return node;
    }

    public Project transform(Project node) {
        return node;
    }

    public Expression transform(ArrayStoreExpression node) {
        return node;
    }

    public Expression transform(StringLiteral node) {
        return node;
    }

    public LeftHandSide transform(ArrayLHS node) {
        return node;
    }

    public Statement transform(AssertStatement node) {
        return node;
    }

    public Specification transform(ModifiesSpecification node) {
        return node;
    }

    public Specification transform(RequiresSpecification node) {
        return node;
    }

    public Attribute transform(Attribute node) {
        return node;
    }

    public ASTType transform(NamedType node) {
        return node;
    }

    public Expression transform(BooleanLiteral node) {
        return node;
    }

    public Expression transform(UnaryExpression node) {
        return node;
    }

    public Expression transform(QuantifierExpression node) {
        return node;
    }

    public Statement transform(WhileStatement node) {
        return node;
    }

    public LeftHandSide transform(StructLHS node) {
        return node;
    }

    public Declaration transform(ConstDeclaration node) {
        return node;
    }

    public Declaration transform(FunctionDeclaration node) {
        return node;
    }

    public Expression transform(RealLiteral node) {
        return node;
    }

    public Statement transform(GotoStatement node) {
        return node;
    }

    public Declaration transform(VariableDeclaration node) {
        return node;
    }

    public Declaration transform(Declaration node) {
        return node;
    }

    public Body transform(Body node) {
        return node;
    }

    public Expression transform(StructConstructor node) {
        return node;
    }

    public Statement transform(AtomicStatement node) {
        return node;
    }

    public ASTType transform(ASTType node) {
        return node;
    }

    public Expression transform(BitvecLiteral node) {
        return node;
    }

    public Statement transform(AssumeStatement node) {
        return node;
    }

    public Statement transform(Statement node) {
        return node;
    }

    public Specification transform(Specification node) {
        return node;
    }

    public Expression transform(IfThenElseExpression node) {
        return node;
    }

    public Expression transform(IdentifierExpression node) {
        return node;
    }

    public Statement transform(BreakStatement node) {
        return node;
    }

    public Expression transform(Expression node) {
        return node;
    }

    public Expression transform(BitVectorAccessExpression node) {
        return node;
    }

    public Declaration transform(TypeDeclaration node) {
        return node;
    }

    public Expression transform(ArrayAccessExpression node) {
        return node;
    }

    public Statement transform(HavocStatement node) {
        return node;
    }
}
