/* GotoStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * A goto statement. This can be a non-deterministic goto with
 * several labels.
 */
public class GotoStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(GotoStatement.class);
    /**
     * A list of labels. Execution continues non-deterministically at
     * one of the labels from the list.
     */
    String[] labels;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param labels a list of labels.
     */
    public GotoStatement(ILocation loc, String[] labels) {
        super(loc);
        this.labels = labels;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid GotoStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("GotoStatement").append('[');
        if (labels == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < labels.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(labels[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets a list of labels. Execution continues non-deterministically at
     * one of the labels from the list.
     * @return a list of labels.
     */
    public String[] getLabels() {
        return labels;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
