/* HavocStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Destroy the contents of variables by over-writing them
 * with non-deterministically chosen values.
 */
public class HavocStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(HavocStatement.class);
    /**
     * The identifiers of this havoc statement.
     */
    VariableLHS[] identifiers;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param identifiers the identifiers of this havoc statement.
     */
    public HavocStatement(ILocation loc, VariableLHS[] identifiers) {
        super(loc);
        this.identifiers = identifiers;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid HavocStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("HavocStatement").append('[');
        if (identifiers == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < identifiers.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(identifiers[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the identifiers of this havoc statement.
     * @return the identifiers of this havoc statement.
     */
    public VariableLHS[] getIdentifiers() {
        return identifiers;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(identifiers!=null){
            children.addAll(Arrays.asList(identifiers));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(identifiers!=null){
                for (VariableLHS elem : identifiers) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<VariableLHS> tmpListnewidentifiers = new ArrayList<>();
        if(identifiers != null){
            for(VariableLHS elem : identifiers){
                VariableLHS newidentifiers = (VariableLHS)elem.accept(visitor);
                isChanged = isChanged || newidentifiers != elem;
                tmpListnewidentifiers.add(newidentifiers);
            }
        }
        if(isChanged){
            return new HavocStatement(loc, tmpListnewidentifiers.toArray(new VariableLHS[0]));
        }
        return this;
    }
}
