/* IdentifierExpression -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.ast.DeclarationInformation;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a read operation of some identifier. The identifier
 * can be anything declared by a {@see VarList} that is visible in
 * the current scope, i.e., global constants, variables, input
 * or output parameters of procedures, local variables,
 * and input parameters of
 * functions (output parameters of functions are not readable).
 */
public class IdentifierExpression extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(IdentifierExpression.class);
    /**
     * The identifier of this identifier expression.
     */
    String identifier;

    /**
     * The declaration information of this identifier expression.
     */
    DeclarationInformation declarationInformation;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param identifier the identifier of this identifier expression.
     */
    public IdentifierExpression(ILocation loc, String identifier) {
        super(loc);
        this.identifier = identifier;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid IdentifierExpression: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param identifier the identifier of this identifier expression.
     * @param declarationInformation the declaration information of this identifier expression.
     */
    public IdentifierExpression(ILocation loc, IBoogieType type, String identifier, DeclarationInformation declarationInformation) {
        super(loc, type);
        this.identifier = identifier;
        this.declarationInformation = declarationInformation;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid IdentifierExpression: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("IdentifierExpression").append('[');
        sb.append(identifier);
        sb.append(',').append(declarationInformation);
        return sb.append(']').toString();
    }

    /**
     * Gets the identifier of this identifier expression.
     * @return the identifier of this identifier expression.
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Gets the declaration information of this identifier expression.
     * @return the declaration information of this identifier expression.
     */
    public DeclarationInformation getDeclarationInformation() {
        return declarationInformation;
    }

    /**
     * Sets the declaration information of this identifier expression.
     * @param declarationInformation the declaration information of this identifier expression.
     */
    public void setDeclarationInformation(DeclarationInformation declarationInformation) {
        //Writeable only once
        if(this.declarationInformation != null && declarationInformation != this.declarationInformation){
                throw new AssertionError("Value is only writeable once");
        }
        this.declarationInformation = declarationInformation;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
