/* IfStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * An if statements. The condition is evaluated and according to
 * the result either the then part or else part is executed. Note
 * that the condition cannot have side-effects.
 */
public class IfStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(IfStatement.class);
    /**
     * The condition. It can be
     * a {@link WildcardExpression} to indicate non-deterministic
     * control flow.
     */
    Expression condition;

    /**
     * The then part of this if statement.
     */
    Statement[] thenPart;

    /**
     * The else part of this if statement.
     */
    Statement[] elsePart;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param condition the condition.
     * @param thenPart the then part of this if statement.
     * @param elsePart the else part of this if statement.
     */
    public IfStatement(ILocation loc, Expression condition, Statement[] thenPart, Statement[] elsePart) {
        super(loc);
        this.condition = condition;
        this.thenPart = thenPart;
        this.elsePart = elsePart;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid IfStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("IfStatement").append('[');
        sb.append(condition);
        sb.append(',');
        if (thenPart == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < thenPart.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(thenPart[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (elsePart == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < elsePart.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(elsePart[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the condition. It can be
     * a {@link WildcardExpression} to indicate non-deterministic
     * control flow.
     * @return the condition.
     */
    public Expression getCondition() {
        return condition;
    }

    /**
     * Gets the then part of this if statement.
     * @return the then part of this if statement.
     */
    public Statement[] getThenPart() {
        return thenPart;
    }

    /**
     * Gets the else part of this if statement.
     * @return the else part of this if statement.
     */
    public Statement[] getElsePart() {
        return elsePart;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(condition);
        if(thenPart!=null){
            children.addAll(Arrays.asList(thenPart));
        }
        if(elsePart!=null){
            children.addAll(Arrays.asList(elsePart));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(condition!=null){
                condition.accept(visitor);
            }
            if(thenPart!=null){
                for (Statement elem : thenPart) {
                    elem.accept(visitor);
                }
            }
            if(elsePart!=null){
                for (Statement elem : elsePart) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

            Expression newcondition = null;
        if(condition != null){
            newcondition = (Expression)condition.accept(visitor);
        }
        boolean isChanged=false;
            ArrayList<Statement> tmpListnewthenPart = new ArrayList<>();
        if(thenPart != null){
            for(Statement elem : thenPart){
                Statement newthenPart = (Statement)elem.accept(visitor);
                isChanged = isChanged || newthenPart != elem;
                tmpListnewthenPart.add(newthenPart);
            }
        }
            ArrayList<Statement> tmpListnewelsePart = new ArrayList<>();
        if(elsePart != null){
            for(Statement elem : elsePart){
                Statement newelsePart = (Statement)elem.accept(visitor);
                isChanged = isChanged || newelsePart != elem;
                tmpListnewelsePart.add(newelsePart);
            }
        }
        if(isChanged || condition != newcondition){
            return new IfStatement(loc, newcondition, tmpListnewthenPart.toArray(new Statement[0]), tmpListnewelsePart.toArray(new Statement[0]));
        }
        return this;
    }
}
