/* IntegerLiteral -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a integer literal which is a special form of a expression.
 */
public class IntegerLiteral extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(IntegerLiteral.class);
    /**
     * The integer given as String. This representation is used to support
     * arbitrarily large numbers. We do not need to compute with them but
     * give them 1-1 to the decision procedure.
     */
    String value;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param value the integer given as String.
     */
    public IntegerLiteral(ILocation loc, String value) {
        super(loc);
        this.value = value;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid IntegerLiteral: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param value the integer given as String.
     */
    public IntegerLiteral(ILocation loc, IBoogieType type, String value) {
        super(loc, type);
        this.value = value;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid IntegerLiteral: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("IntegerLiteral").append('[');
        sb.append(value);
        return sb.append(']').toString();
    }

    /**
     * Gets the integer given as String. This representation is used to support
     * arbitrarily large numbers. We do not need to compute with them but
     * give them 1-1 to the decision procedure.
     * @return the integer given as String.
     */
    public String getValue() {
        return value;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
