/* JoinStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * A join statement waits for a procedure (which was called
 * with fork before) to terminate.
 */
public class JoinStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(JoinStatement.class);
    /**
     * The id or list of id's of the fork expression, to which the join statement
     * is referring to.
     */
    Expression[] threadID;

    /**
     * The variables where the return values are written to.
     */
    VariableLHS[] lhs;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param threadID the id or list of id's of the fork expression, to which the join statement
     * is referring to.
     * @param lhs the variables where the return values are written to.
     */
    public JoinStatement(ILocation loc, Expression[] threadID, VariableLHS[] lhs) {
        super(loc);
        this.threadID = threadID;
        this.lhs = lhs;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid JoinStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("JoinStatement").append('[');
        if (threadID == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < threadID.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(threadID[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (lhs == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < lhs.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(lhs[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the id or list of id's of the fork expression, to which the join statement
     * is referring to.
     * @return the id or list of id's of the fork expression, to which the join statement
     * is referring to.
     */
    public Expression[] getThreadID() {
        return threadID;
    }

    /**
     * Gets the variables where the return values are written to.
     * @return the variables where the return values are written to.
     */
    public VariableLHS[] getLhs() {
        return lhs;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(threadID!=null){
            children.addAll(Arrays.asList(threadID));
        }
        if(lhs!=null){
            children.addAll(Arrays.asList(lhs));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(threadID!=null){
                for (Expression elem : threadID) {
                    elem.accept(visitor);
                }
            }
            if(lhs!=null){
                for (VariableLHS elem : lhs) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<Expression> tmpListnewthreadID = new ArrayList<>();
        if(threadID != null){
            for(Expression elem : threadID){
                Expression newthreadID = (Expression)elem.accept(visitor);
                isChanged = isChanged || newthreadID != elem;
                tmpListnewthreadID.add(newthreadID);
            }
        }
            ArrayList<VariableLHS> tmpListnewlhs = new ArrayList<>();
        if(lhs != null){
            for(VariableLHS elem : lhs){
                VariableLHS newlhs = (VariableLHS)elem.accept(visitor);
                isChanged = isChanged || newlhs != elem;
                tmpListnewlhs.add(newlhs);
            }
        }
        if(isChanged){
            return new JoinStatement(loc, tmpListnewthreadID.toArray(new Expression[0]), tmpListnewlhs.toArray(new VariableLHS[0]));
        }
        return this;
    }
}
