/* Label -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a label. We see labels as statements of their own,
 * that do nothing and let the program continue with the
 * statement that follows it.
 */
public class Label extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Label.class);
    /**
     * The name of this label.
     */
    String name;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param name the name of this label.
     */
    public Label(ILocation loc, String name) {
        super(loc);
        this.name = name;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Label: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Label").append('[');
        sb.append(name);
        return sb.append(']').toString();
    }

    /**
     * Gets the name of this label.
     * @return the name of this label.
     */
    public String getName() {
        return name;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
