/* LeftHandSide -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * The left hand side represents an object that can appear on the
 * left-hand side of an assignment. In Boogie this can be variables
 * ({@link VariableLHS} or array elements {@link ArrayLHS}. Our
 * extension also allows struct fields {@link StructLHS}.
 */
public abstract class LeftHandSide extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(LeftHandSide.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * The type of the object, i.e., the type that can be stored
     * in the object. This is computed by the type checker. You
     * can set it to null, if you call the type checker afterwards.
     */
    IBoogieType type;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     */
    public LeftHandSide(ILocation loc) {
        super(loc);
        this.loc = loc;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid LeftHandSide: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of the object, i.
     */
    public LeftHandSide(ILocation loc, IBoogieType type) {
        super(loc);
        this.loc = loc;
        this.type = type;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid LeftHandSide: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("LeftHandSide").append('[');
        sb.append(loc);
        sb.append(',').append(type);
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Gets the type of the object, i.e., the type that can be stored
     * in the object. This is computed by the type checker. You
     * can set it to null, if you call the type checker afterwards.
     * @return the type of the object, i.
     */
    public IBoogieType getType() {
        return type;
    }

    /**
     * Sets the type of the object, i.e., the type that can be stored
     * in the object. This is computed by the type checker. You
     * can set it to null, if you call the type checker afterwards.
     * @param type the type of the object, i.
     */
    public void setType(IBoogieType type) {
        this.type = type;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public abstract void accept(GeneratedBoogieAstVisitor visitor);

    public abstract LeftHandSide accept(GeneratedBoogieAstTransformer visitor);
}
