/* ModifiesSpecification -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a modifies specification which is a special form of a specification.
 */
public class ModifiesSpecification extends Specification {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(ModifiesSpecification.class);
    /**
     * The identifiers of this modifies specification.
     */
    VariableLHS[] identifiers;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param isFree true iff this specification is free.
     * @param identifiers the identifiers of this modifies specification.
     */
    public ModifiesSpecification(ILocation loc, boolean isFree, VariableLHS[] identifiers) {
        super(loc, isFree);
        this.identifiers = identifiers;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ModifiesSpecification: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("ModifiesSpecification").append('[');
        if (identifiers == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < identifiers.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(identifiers[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the identifiers of this modifies specification.
     * @return the identifiers of this modifies specification.
     */
    public VariableLHS[] getIdentifiers() {
        return identifiers;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(identifiers!=null){
            children.addAll(Arrays.asList(identifiers));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Specification)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(identifiers!=null){
                for (VariableLHS elem : identifiers) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Specification accept(GeneratedBoogieAstTransformer visitor) {
        Specification node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<VariableLHS> tmpListnewidentifiers = new ArrayList<>();
        if(identifiers != null){
            for(VariableLHS elem : identifiers){
                VariableLHS newidentifiers = (VariableLHS)elem.accept(visitor);
                isChanged = isChanged || newidentifiers != elem;
                tmpListnewidentifiers.add(newidentifiers);
            }
        }
        if(isChanged){
            return new ModifiesSpecification(loc, isFree, tmpListnewidentifiers.toArray(new VariableLHS[0]));
        }
        return this;
    }
}
