/* NamedAttribute -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a named attribute which is a special form of a attribute.
 */
public class NamedAttribute extends Attribute {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(NamedAttribute.class);
    /**
     * The name of this named attribute.
     */
    String name;

    /**
     * The values of this named attribute.
     */
    Expression[] values;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param name the name of this named attribute.
     * @param values the values of this named attribute.
     */
    public NamedAttribute(ILocation loc, String name, Expression[] values) {
        super(loc);
        this.name = name;
        this.values = values;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid NamedAttribute: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("NamedAttribute").append('[');
        sb.append(name);
        sb.append(',');
        if (values == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < values.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(values[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the name of this named attribute.
     * @return the name of this named attribute.
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the values of this named attribute.
     * @return the values of this named attribute.
     */
    public Expression[] getValues() {
        return values;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(values!=null){
            children.addAll(Arrays.asList(values));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Attribute)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(values!=null){
                for (Expression elem : values) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Attribute accept(GeneratedBoogieAstTransformer visitor) {
        Attribute node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<Expression> tmpListnewvalues = new ArrayList<>();
        if(values != null){
            for(Expression elem : values){
                Expression newvalues = (Expression)elem.accept(visitor);
                isChanged = isChanged || newvalues != elem;
                tmpListnewvalues.add(newvalues);
            }
        }
        if(isChanged){
            return new NamedAttribute(loc, name, tmpListnewvalues.toArray(new Expression[0]));
        }
        return this;
    }
}
