/* NamedType -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a named type which is a special form of a a s t type.
 */
public class NamedType extends ASTType {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(NamedType.class);
    /**
     * The name of this named type.
     */
    String name;

    /**
     * The type args of this named type.
     */
    ASTType[] typeArgs;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param name the name of this named type.
     * @param typeArgs the type args of this named type.
     */
    public NamedType(ILocation loc, String name, ASTType[] typeArgs) {
        super(loc);
        this.name = name;
        this.typeArgs = typeArgs;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid NamedType: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param boogieType the semantic type that is represented by this type.
     * @param name the name of this named type.
     * @param typeArgs the type args of this named type.
     */
    public NamedType(ILocation loc, IBoogieType boogieType, String name, ASTType[] typeArgs) {
        super(loc, boogieType);
        this.name = name;
        this.typeArgs = typeArgs;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid NamedType: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("NamedType").append('[');
        sb.append(name);
        sb.append(',');
        if (typeArgs == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < typeArgs.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(typeArgs[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the name of this named type.
     * @return the name of this named type.
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the type args of this named type.
     * @return the type args of this named type.
     */
    public ASTType[] getTypeArgs() {
        return typeArgs;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(typeArgs!=null){
            children.addAll(Arrays.asList(typeArgs));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((ASTType)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(typeArgs!=null){
                for (ASTType elem : typeArgs) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public ASTType accept(GeneratedBoogieAstTransformer visitor) {
        ASTType node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<ASTType> tmpListnewtypeArgs = new ArrayList<>();
        if(typeArgs != null){
            for(ASTType elem : typeArgs){
                ASTType newtypeArgs = (ASTType)elem.accept(visitor);
                isChanged = isChanged || newtypeArgs != elem;
                tmpListnewtypeArgs.add(newtypeArgs);
            }
        }
        if(isChanged){
            return new NamedType(loc, boogieType, name, tmpListnewtypeArgs.toArray(new ASTType[0]));
        }
        return this;
    }
}
