/* ParentEdge -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a parent edge.
 */
public class ParentEdge extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(ParentEdge.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * True if this parent edge is unique. In that case the
     * <emph>children</emph> of this constant are disjoint from
     * the children of any other constant declared with the
     * same unique parentNode.
     */
    boolean isUnique;

    /**
     * The name of the parent.
     */
    String identifier;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param isUnique true if this parent edge is unique.
     * @param identifier the name of the parent.
     */
    public ParentEdge(ILocation loc, boolean isUnique, String identifier) {
        super(loc);
        this.loc = loc;
        this.isUnique = isUnique;
        this.identifier = identifier;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ParentEdge: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("ParentEdge").append('[');
        sb.append(loc);
        sb.append(',').append(isUnique);
        sb.append(',').append(identifier);
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Checks if this parent edge is unique. In that case the
     * <emph>children</emph> of this constant are disjoint from
     * the children of any other constant declared with the
     * same unique parentNode.
     * @return true if this parent edge is unique.
     */
    public boolean isUnique() {
        return isUnique;
    }

    /**
     * Gets the name of the parent.
     * @return the name of the parent.
     */
    public String getIdentifier() {
        return identifier;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        visitor.visit(this);
    }

    public ParentEdge accept(GeneratedBoogieAstTransformer visitor) {
        ParentEdge node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
