/* PrimitiveType -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * This class is used to represent primitive types. This must only
 * be used for the builtin types <code>bool, int, real,
 * and bv[0-9]</code> (the last stands for the bit-vector types).
 * 
 * All other non-array and non-structure types are represented as
 * {@link NamedType named type}.
 */
public class PrimitiveType extends ASTType {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(PrimitiveType.class);
    /**
     * The name of this primitive type.
     */
    String name;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param name the name of this primitive type.
     */
    public PrimitiveType(ILocation loc, String name) {
        super(loc);
        this.name = name;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid PrimitiveType: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param boogieType the semantic type that is represented by this type.
     * @param name the name of this primitive type.
     */
    public PrimitiveType(ILocation loc, IBoogieType boogieType, String name) {
        super(loc, boogieType);
        this.name = name;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid PrimitiveType: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("PrimitiveType").append('[');
        sb.append(name);
        return sb.append(']').toString();
    }

    /**
     * Gets the name of this primitive type.
     * @return the name of this primitive type.
     */
    public String getName() {
        return name;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((ASTType)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public ASTType accept(GeneratedBoogieAstTransformer visitor) {
        ASTType node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
