/* Procedure -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a procedure or an implementation.
 * 
 * An implementation does not have specifications, i.e.
 * getSpecification() returns null. A procedure must
 * have a specification, but does not need an implementation,
 * i.e., body may be null. Procedures can also contain both
 * specification and implementation.
 */
public class Procedure extends Declaration {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Procedure.class);
    /**
     * The name of the procedure.
     */
    String identifier;

    /**
     * The type parameters. This is used for polymorphic procedures.
     * For non-polymorphic procedures the array is empty.
     */
    String[] typeParams;

    /**
     * The input parameters.
     */
    VarList[] inParams;

    /**
     * The output parameters.
     */
    VarList[] outParams;

    /**
     * The specification. It is null for an implementation and
     * != null (but its length may be 0) for a procedure.
     */
    Specification[] specification;

    /**
     * The body. If this is an implementation (getSpecification() returns null)
     * this must be present, otherwise it is optional.
     */
    Body body;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param attributes the implementation specific attributes of this declaration.
     * @param identifier the name of the procedure.
     * @param typeParams the type parameters.
     * @param inParams the input parameters.
     * @param outParams the output parameters.
     * @param specification the specification.
     * @param body the body.
     */
    public Procedure(ILocation loc, Attribute[] attributes, String identifier, String[] typeParams, VarList[] inParams, VarList[] outParams, Specification[] specification, Body body) {
        super(loc, attributes);
        this.identifier = identifier;
        this.typeParams = typeParams;
        this.inParams = inParams;
        this.outParams = outParams;
        this.specification = specification;
        this.body = body;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Procedure: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Procedure").append('[');
        sb.append(identifier);
        sb.append(',');
        if (typeParams == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < typeParams.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(typeParams[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (inParams == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < inParams.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(inParams[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (outParams == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < outParams.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(outParams[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (specification == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < specification.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(specification[i1]);
            }
            sb.append(']');
        }
        sb.append(',').append(body);
        return sb.append(']').toString();
    }

    /**
     * Gets the name of the procedure.
     * @return the name of the procedure.
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Gets the type parameters. This is used for polymorphic procedures.
     * For non-polymorphic procedures the array is empty.
     * @return the type parameters.
     */
    public String[] getTypeParams() {
        return typeParams;
    }

    /**
     * Gets the input parameters.
     * @return the input parameters.
     */
    public VarList[] getInParams() {
        return inParams;
    }

    /**
     * Gets the output parameters.
     * @return the output parameters.
     */
    public VarList[] getOutParams() {
        return outParams;
    }

    /**
     * Gets the specification. It is null for an implementation and
     * != null (but its length may be 0) for a procedure.
     * @return the specification.
     */
    public Specification[] getSpecification() {
        return specification;
    }

    /**
     * Sets the specification. It is null for an implementation and
     * != null (but its length may be 0) for a procedure.
     * @param specification the specification.
     */
    public void setSpecification(Specification[] specification) {
        this.specification = specification;
    }

    /**
     * Gets the body. If this is an implementation (getSpecification() returns null)
     * this must be present, otherwise it is optional.
     * @return the body.
     */
    public Body getBody() {
        return body;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(inParams!=null){
            children.addAll(Arrays.asList(inParams));
        }
        if(outParams!=null){
            children.addAll(Arrays.asList(outParams));
        }
        if(specification!=null){
            children.addAll(Arrays.asList(specification));
        }
        children.add(body);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Declaration)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(inParams!=null){
                for (VarList elem : inParams) {
                    elem.accept(visitor);
                }
            }
            if(outParams!=null){
                for (VarList elem : outParams) {
                    elem.accept(visitor);
                }
            }
            if(specification!=null){
                for (Specification elem : specification) {
                    elem.accept(visitor);
                }
            }
            if(body!=null){
                body.accept(visitor);
            }
            if(attributes!=null){
                for (Attribute elem : attributes) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Declaration accept(GeneratedBoogieAstTransformer visitor) {
        Declaration node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<VarList> tmpListnewinParams = new ArrayList<>();
        if(inParams != null){
            for(VarList elem : inParams){
                VarList newinParams = (VarList)elem.accept(visitor);
                isChanged = isChanged || newinParams != elem;
                tmpListnewinParams.add(newinParams);
            }
        }
            ArrayList<VarList> tmpListnewoutParams = new ArrayList<>();
        if(outParams != null){
            for(VarList elem : outParams){
                VarList newoutParams = (VarList)elem.accept(visitor);
                isChanged = isChanged || newoutParams != elem;
                tmpListnewoutParams.add(newoutParams);
            }
        }
            ArrayList<Specification> tmpListnewspecification = new ArrayList<>();
        if(specification != null){
            for(Specification elem : specification){
                Specification newspecification = (Specification)elem.accept(visitor);
                isChanged = isChanged || newspecification != elem;
                tmpListnewspecification.add(newspecification);
            }
        }
            Body newbody = null;
        if(body != null){
            newbody = (Body)body.accept(visitor);
        }
            ArrayList<Attribute> tmpListnewattributes = new ArrayList<>();
        if(attributes != null){
            for(Attribute elem : attributes){
                Attribute newattributes = (Attribute)elem.accept(visitor);
                isChanged = isChanged || newattributes != elem;
                tmpListnewattributes.add(newattributes);
            }
        }
        if(isChanged || body != newbody){
            return new Procedure(loc, tmpListnewattributes.toArray(new Attribute[0]), identifier, typeParams, tmpListnewinParams.toArray(new VarList[0]), tmpListnewoutParams.toArray(new VarList[0]), tmpListnewspecification.toArray(new Specification[0]), newbody);
        }
        return this;
    }
}
