/* Project -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a project.
 */
public class Project extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Project.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * The units of this project.
     */
    Unit[] units;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param units the units of this project.
     */
    public Project(ILocation loc, Unit[] units) {
        super(loc);
        this.loc = loc;
        this.units = units;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Project: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Project").append('[');
        sb.append(loc);
        sb.append(',');
        if (units == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < units.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(units[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Gets the units of this project.
     * @return the units of this project.
     */
    public Unit[] getUnits() {
        return units;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(units!=null){
            children.addAll(Arrays.asList(units));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit(this)) {
            if(units!=null){
                for (Unit elem : units) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Project accept(GeneratedBoogieAstTransformer visitor) {
        Project node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<Unit> tmpListnewunits = new ArrayList<>();
        if(units != null){
            for(Unit elem : units){
                Unit newunits = (Unit)elem.accept(visitor);
                isChanged = isChanged || newunits != elem;
                tmpListnewunits.add(newunits);
            }
        }
        if(isChanged){
            return new Project(loc, tmpListnewunits.toArray(new Unit[0]));
        }
        return this;
    }
}
