/* QuantifierExpression -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a quantifier expression which is a special form of a expression.
 */
public class QuantifierExpression extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(QuantifierExpression.class);
    /**
     * This is true for universal and false for existential quantifier.
     */
    boolean isUniversal;

    /**
     * The type params of this quantifier expression.
     */
    String[] typeParams;

    /**
     * The parameters of this quantifier expression.
     */
    VarList[] parameters;

    /**
     * The attributes of this quantifier expression.
     */
    Attribute[] attributes;

    /**
     * The subformula of this quantifier expression.
     */
    Expression subformula;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param isUniversal this is true for universal and false for existential quantifier.
     * @param typeParams the type params of this quantifier expression.
     * @param parameters the parameters of this quantifier expression.
     * @param attributes the attributes of this quantifier expression.
     * @param subformula the subformula of this quantifier expression.
     */
    public QuantifierExpression(ILocation loc, boolean isUniversal, String[] typeParams, VarList[] parameters, Attribute[] attributes, Expression subformula) {
        super(loc);
        this.isUniversal = isUniversal;
        this.typeParams = typeParams;
        this.parameters = parameters;
        this.attributes = attributes;
        this.subformula = subformula;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid QuantifierExpression: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param isUniversal this is true for universal and false for existential quantifier.
     * @param typeParams the type params of this quantifier expression.
     * @param parameters the parameters of this quantifier expression.
     * @param attributes the attributes of this quantifier expression.
     * @param subformula the subformula of this quantifier expression.
     */
    public QuantifierExpression(ILocation loc, IBoogieType type, boolean isUniversal, String[] typeParams, VarList[] parameters, Attribute[] attributes, Expression subformula) {
        super(loc, type);
        this.isUniversal = isUniversal;
        this.typeParams = typeParams;
        this.parameters = parameters;
        this.attributes = attributes;
        this.subformula = subformula;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid QuantifierExpression: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("QuantifierExpression").append('[');
        sb.append(isUniversal);
        sb.append(',');
        if (typeParams == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < typeParams.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(typeParams[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (parameters == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < parameters.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(parameters[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (attributes == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < attributes.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(attributes[i1]);
            }
            sb.append(']');
        }
        sb.append(',').append(subformula);
        return sb.append(']').toString();
    }

    /**
     * Checks this is true for universal and false for existential quantifier.
     * @return this is true for universal and false for existential quantifier.
     */
    public boolean isUniversal() {
        return isUniversal;
    }

    /**
     * Gets the type params of this quantifier expression.
     * @return the type params of this quantifier expression.
     */
    public String[] getTypeParams() {
        return typeParams;
    }

    /**
     * Gets the parameters of this quantifier expression.
     * @return the parameters of this quantifier expression.
     */
    public VarList[] getParameters() {
        return parameters;
    }

    /**
     * Gets the attributes of this quantifier expression.
     * @return the attributes of this quantifier expression.
     */
    public Attribute[] getAttributes() {
        return attributes;
    }

    /**
     * Gets the subformula of this quantifier expression.
     * @return the subformula of this quantifier expression.
     */
    public Expression getSubformula() {
        return subformula;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(parameters!=null){
            children.addAll(Arrays.asList(parameters));
        }
        if(attributes!=null){
            children.addAll(Arrays.asList(attributes));
        }
        children.add(subformula);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(parameters!=null){
                for (VarList elem : parameters) {
                    elem.accept(visitor);
                }
            }
            if(attributes!=null){
                for (Attribute elem : attributes) {
                    elem.accept(visitor);
                }
            }
            if(subformula!=null){
                subformula.accept(visitor);
            }
        }
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<VarList> tmpListnewparameters = new ArrayList<>();
        if(parameters != null){
            for(VarList elem : parameters){
                VarList newparameters = (VarList)elem.accept(visitor);
                isChanged = isChanged || newparameters != elem;
                tmpListnewparameters.add(newparameters);
            }
        }
            ArrayList<Attribute> tmpListnewattributes = new ArrayList<>();
        if(attributes != null){
            for(Attribute elem : attributes){
                Attribute newattributes = (Attribute)elem.accept(visitor);
                isChanged = isChanged || newattributes != elem;
                tmpListnewattributes.add(newattributes);
            }
        }
            Expression newsubformula = null;
        if(subformula != null){
            newsubformula = (Expression)subformula.accept(visitor);
        }
        if(isChanged || subformula != newsubformula){
            return new QuantifierExpression(loc, type, isUniversal, typeParams, tmpListnewparameters.toArray(new VarList[0]), tmpListnewattributes.toArray(new Attribute[0]), newsubformula);
        }
        return this;
    }
}
