/* ReturnStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * The return statement terminates the current procedure.
 */
public class ReturnStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(ReturnStatement.class);
    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     */
    public ReturnStatement(ILocation loc) {
        super(loc);
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid ReturnStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        return "ReturnStatement";
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
