/* Specification -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a specification.
 */
public abstract class Specification extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Specification.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * True iff this specification is free.
     */
    boolean isFree;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param isFree true iff this specification is free.
     */
    public Specification(ILocation loc, boolean isFree) {
        super(loc);
        this.loc = loc;
        this.isFree = isFree;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Specification: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Specification").append('[');
        sb.append(loc);
        sb.append(',').append(isFree);
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Checks iff this specification is free.
     * @return true iff this specification is free.
     */
    public boolean isFree() {
        return isFree;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public abstract void accept(GeneratedBoogieAstVisitor visitor);

    public abstract Specification accept(GeneratedBoogieAstTransformer visitor);
}
