/* StringLiteral -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a string literal.
 * This is only used as attribute value, since strings are not otherwise
 * supported in Boogie. A string literal never has a type.
 */
public class StringLiteral extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(StringLiteral.class);
    /**
     * The value of this string literal.
     */
    String value;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param value the value of this string literal.
     */
    public StringLiteral(ILocation loc, String value) {
        super(loc);
        this.value = value;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StringLiteral: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param value the value of this string literal.
     */
    public StringLiteral(ILocation loc, IBoogieType type, String value) {
        super(loc, type);
        this.value = value;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StringLiteral: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("StringLiteral").append('[');
        sb.append(value);
        return sb.append(']').toString();
    }

    /**
     * Gets the value of this string literal.
     * @return the value of this string literal.
     */
    public String getValue() {
        return value;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
