/* StructType -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a struct type which is a special form of a a s t type.
 */
public class StructType extends ASTType {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(StructType.class);
    /**
     * Array of the struct fields.
     */
    VarList[] fields;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param fields array of the struct fields.
     */
    public StructType(ILocation loc, VarList[] fields) {
        super(loc);
        this.fields = fields;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StructType: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param boogieType the semantic type that is represented by this type.
     * @param fields array of the struct fields.
     */
    public StructType(ILocation loc, IBoogieType boogieType, VarList[] fields) {
        super(loc, boogieType);
        this.fields = fields;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StructType: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("StructType").append('[');
        if (fields == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < fields.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(fields[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets array of the struct fields.
     * @return array of the struct fields.
     */
    public VarList[] getFields() {
        return fields;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(fields!=null){
            children.addAll(Arrays.asList(fields));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((ASTType)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(fields!=null){
                for (VarList elem : fields) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public ASTType accept(GeneratedBoogieAstTransformer visitor) {
        ASTType node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<VarList> tmpListnewfields = new ArrayList<>();
        if(fields != null){
            for(VarList elem : fields){
                VarList newfields = (VarList)elem.accept(visitor);
                isChanged = isChanged || newfields != elem;
                tmpListnewfields.add(newfields);
            }
        }
        if(isChanged){
            return new StructType(loc, boogieType, tmpListnewfields.toArray(new VarList[0]));
        }
        return this;
    }
}
