/* StructAccessExpression -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a struct access expression which is a special form of a expression.
 */
public class StructAccessExpression extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(StructAccessExpression.class);
    /**
     * The struct of this struct access expression.
     */
    Expression struct;

    /**
     * The field of this struct access expression.
     */
    String field;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param struct the struct of this struct access expression.
     * @param field the field of this struct access expression.
     */
    public StructAccessExpression(ILocation loc, Expression struct, String field) {
        super(loc);
        this.struct = struct;
        this.field = field;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StructAccessExpression: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param struct the struct of this struct access expression.
     * @param field the field of this struct access expression.
     */
    public StructAccessExpression(ILocation loc, IBoogieType type, Expression struct, String field) {
        super(loc, type);
        this.struct = struct;
        this.field = field;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StructAccessExpression: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("StructAccessExpression").append('[');
        sb.append(struct);
        sb.append(',').append(field);
        return sb.append(']').toString();
    }

    /**
     * Gets the struct of this struct access expression.
     * @return the struct of this struct access expression.
     */
    public Expression getStruct() {
        return struct;
    }

    /**
     * Gets the field of this struct access expression.
     * @return the field of this struct access expression.
     */
    public String getField() {
        return field;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(struct);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(struct!=null){
                struct.accept(visitor);
            }
        }
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

            Expression newstruct = null;
        if(struct != null){
            newstruct = (Expression)struct.accept(visitor);
        }
        if(struct != newstruct){
            return new StructAccessExpression(loc, type, newstruct, field);
        }
        return this;
    }
}
