/* StructLHS -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * A struct left-hand-side represents a field of an array.
 */
public class StructLHS extends LeftHandSide {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(StructLHS.class);
    /**
     * The struct whose field we represent.
     */
    LeftHandSide struct;

    /**
     * The name of the field.
     */
    String field;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param struct the struct whose field we represent.
     * @param field the name of the field.
     */
    public StructLHS(ILocation loc, LeftHandSide struct, String field) {
        super(loc);
        this.struct = struct;
        this.field = field;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StructLHS: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of the object, i.
     * @param struct the struct whose field we represent.
     * @param field the name of the field.
     */
    public StructLHS(ILocation loc, IBoogieType type, LeftHandSide struct, String field) {
        super(loc, type);
        this.struct = struct;
        this.field = field;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StructLHS: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("StructLHS").append('[');
        sb.append(struct);
        sb.append(',').append(field);
        return sb.append(']').toString();
    }

    /**
     * Gets the struct whose field we represent.
     * @return the struct whose field we represent.
     */
    public LeftHandSide getStruct() {
        return struct;
    }

    /**
     * Gets the name of the field.
     * @return the name of the field.
     */
    public String getField() {
        return field;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(struct);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((LeftHandSide)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(struct!=null){
                struct.accept(visitor);
            }
        }
    }

    public LeftHandSide accept(GeneratedBoogieAstTransformer visitor) {
        LeftHandSide node = visitor.transform(this);
        if(node != this){
            return node;
        }

            LeftHandSide newstruct = null;
        if(struct != null){
            newstruct = (LeftHandSide)struct.accept(visitor);
        }
        if(struct != newstruct){
            return new StructLHS(loc, type, newstruct, field);
        }
        return this;
    }
}
