/* StructConstructor -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a struct constructor.
 */
public class StructConstructor extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(StructConstructor.class);
    /**
     * The field identifiers of this struct constructor.
     */
    String[] fieldIdentifiers;

    /**
     * The field values of this struct constructor.
     */
    Expression[] fieldValues;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param fieldIdentifiers the field identifiers of this struct constructor.
     * @param fieldValues the field values of this struct constructor.
     */
    public StructConstructor(ILocation loc, String[] fieldIdentifiers, Expression[] fieldValues) {
        super(loc);
        this.fieldIdentifiers = fieldIdentifiers;
        this.fieldValues = fieldValues;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StructConstructor: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param fieldIdentifiers the field identifiers of this struct constructor.
     * @param fieldValues the field values of this struct constructor.
     */
    public StructConstructor(ILocation loc, IBoogieType type, String[] fieldIdentifiers, Expression[] fieldValues) {
        super(loc, type);
        this.fieldIdentifiers = fieldIdentifiers;
        this.fieldValues = fieldValues;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid StructConstructor: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("StructConstructor").append('[');
        if (fieldIdentifiers == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < fieldIdentifiers.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(fieldIdentifiers[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (fieldValues == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < fieldValues.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(fieldValues[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the field identifiers of this struct constructor.
     * @return the field identifiers of this struct constructor.
     */
    public String[] getFieldIdentifiers() {
        return fieldIdentifiers;
    }

    /**
     * Gets the field values of this struct constructor.
     * @return the field values of this struct constructor.
     */
    public Expression[] getFieldValues() {
        return fieldValues;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(fieldValues!=null){
            children.addAll(Arrays.asList(fieldValues));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(fieldValues!=null){
                for (Expression elem : fieldValues) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<Expression> tmpListnewfieldValues = new ArrayList<>();
        if(fieldValues != null){
            for(Expression elem : fieldValues){
                Expression newfieldValues = (Expression)elem.accept(visitor);
                isChanged = isChanged || newfieldValues != elem;
                tmpListnewfieldValues.add(newfieldValues);
            }
        }
        if(isChanged){
            return new StructConstructor(loc, type, fieldIdentifiers, tmpListnewfieldValues.toArray(new Expression[0]));
        }
        return this;
    }
}
