/* Trigger -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a trigger which is a special form of a attribute.
 */
public class Trigger extends Attribute {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Trigger.class);
    /**
     * The triggers of this trigger.
     */
    Expression[] triggers;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param triggers the triggers of this trigger.
     */
    public Trigger(ILocation loc, Expression[] triggers) {
        super(loc);
        this.triggers = triggers;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Trigger: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Trigger").append('[');
        if (triggers == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < triggers.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(triggers[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the triggers of this trigger.
     * @return the triggers of this trigger.
     */
    public Expression[] getTriggers() {
        return triggers;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(triggers!=null){
            children.addAll(Arrays.asList(triggers));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Attribute)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(triggers!=null){
                for (Expression elem : triggers) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Attribute accept(GeneratedBoogieAstTransformer visitor) {
        Attribute node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<Expression> tmpListnewtriggers = new ArrayList<>();
        if(triggers != null){
            for(Expression elem : triggers){
                Expression newtriggers = (Expression)elem.accept(visitor);
                isChanged = isChanged || newtriggers != elem;
                tmpListnewtriggers.add(newtriggers);
            }
        }
        if(isChanged){
            return new Trigger(loc, tmpListnewtriggers.toArray(new Expression[0]));
        }
        return this;
    }
}
