/* UnaryExpression -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * Represents a unary expression which is a special form of a expression.
 */
public class UnaryExpression extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(UnaryExpression.class);
    public enum Operator {
        LOGICNEG, ARITHNEGATIVE, OLD
    }

    /**
     * The operator of this unary expression.
     */
    Operator operator;

    /**
     * The expr of this unary expression.
     */
    Expression expr;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param operator the operator of this unary expression.
     * @param expr the expr of this unary expression.
     */
    public UnaryExpression(ILocation loc, Operator operator, Expression expr) {
        super(loc);
        this.operator = operator;
        this.expr = expr;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid UnaryExpression: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     * @param operator the operator of this unary expression.
     * @param expr the expr of this unary expression.
     */
    public UnaryExpression(ILocation loc, IBoogieType type, Operator operator, Expression expr) {
        super(loc, type);
        this.operator = operator;
        this.expr = expr;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid UnaryExpression: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("UnaryExpression").append('[');
        sb.append(operator);
        sb.append(',').append(expr);
        return sb.append(']').toString();
    }

    /**
     * Gets the operator of this unary expression.
     * @return the operator of this unary expression.
     */
    public Operator getOperator() {
        return operator;
    }

    /**
     * Gets the expr of this unary expression.
     * @return the expr of this unary expression.
     */
    public Expression getExpr() {
        return expr;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(expr);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(expr!=null){
                expr.accept(visitor);
            }
        }
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

            Expression newexpr = null;
        if(expr != null){
            newexpr = (Expression)expr.accept(visitor);
        }
        if(expr != newexpr){
            return new UnaryExpression(loc, type, operator, newexpr);
        }
        return this;
    }
}
