/* Unit -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * A Boogie-Unit is representing a Boogie-file. It just consists of
 * a bunch of {@link Declaration Declarations}. The order of the
 * declarations is not relevant. Every declaration is one of
 * {@link TypeDeclaration}, {@link ConstDeclaration},
 * {@link Axiom}, {@link FunctionDeclaration}, {@link VariableDeclaration},
 * or {@link Procedure}.
 */
public class Unit extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(Unit.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * The declarations of this unit.
     */
    Declaration[] declarations;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param declarations the declarations of this unit.
     */
    public Unit(ILocation loc, Declaration[] declarations) {
        super(loc);
        this.loc = loc;
        this.declarations = declarations;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid Unit: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("Unit").append('[');
        sb.append(loc);
        sb.append(',');
        if (declarations == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < declarations.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(declarations[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Gets the declarations of this unit.
     * @return the declarations of this unit.
     */
    public Declaration[] getDeclarations() {
        return declarations;
    }

    /**
     * Sets the declarations of this unit.
     * @param declarations the declarations of this unit.
     */
    public void setDeclarations(Declaration[] declarations) {
        this.declarations = declarations;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(declarations!=null){
            children.addAll(Arrays.asList(declarations));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit(this)) {
            if(declarations!=null){
                for (Declaration elem : declarations) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Unit accept(GeneratedBoogieAstTransformer visitor) {
        Unit node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<Declaration> tmpListnewdeclarations = new ArrayList<>();
        if(declarations != null){
            for(Declaration elem : declarations){
                Declaration newdeclarations = (Declaration)elem.accept(visitor);
                isChanged = isChanged || newdeclarations != elem;
                tmpListnewdeclarations.add(newdeclarations);
            }
        }
        if(isChanged){
            return new Unit(loc, tmpListnewdeclarations.toArray(new Declaration[0]));
        }
        return this;
    }
}
