/* VariableLHS -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.ast.DeclarationInformation;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;

/**
 * A variable left-hand-side represents a variable.
 */
public class VariableLHS extends LeftHandSide {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(VariableLHS.class);
    /**
     * The name of the variable. This can be a global variable,
     * a local variable or an output parameter of a procedure.
     */
    String identifier;

    /**
     * The declaration information of this variable l h s.
     */
    DeclarationInformation declarationInformation;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param identifier the name of the variable.
     */
    public VariableLHS(ILocation loc, String identifier) {
        super(loc);
        this.identifier = identifier;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid VariableLHS: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of the object, i.
     * @param identifier the name of the variable.
     * @param declarationInformation the declaration information of this variable l h s.
     */
    public VariableLHS(ILocation loc, IBoogieType type, String identifier, DeclarationInformation declarationInformation) {
        super(loc, type);
        this.identifier = identifier;
        this.declarationInformation = declarationInformation;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid VariableLHS: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("VariableLHS").append('[');
        sb.append(identifier);
        sb.append(',').append(declarationInformation);
        return sb.append(']').toString();
    }

    /**
     * Gets the name of the variable. This can be a global variable,
     * a local variable or an output parameter of a procedure.
     * @return the name of the variable.
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Gets the declaration information of this variable l h s.
     * @return the declaration information of this variable l h s.
     */
    public DeclarationInformation getDeclarationInformation() {
        return declarationInformation;
    }

    /**
     * Sets the declaration information of this variable l h s.
     * @param declarationInformation the declaration information of this variable l h s.
     */
    public void setDeclarationInformation(DeclarationInformation declarationInformation) {
        //Writeable only once
        if(this.declarationInformation != null && declarationInformation != this.declarationInformation){
                throw new AssertionError("Value is only writeable once");
        }
        this.declarationInformation = declarationInformation;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((LeftHandSide)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public LeftHandSide accept(GeneratedBoogieAstTransformer visitor) {
        LeftHandSide node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
