/* VariableDeclaration -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * A variable declaration declares global variables or local variables.
 */
public class VariableDeclaration extends Declaration {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(VariableDeclaration.class);
    /**
     * The variables of this variable declaration.
     */
    VarList[] variables;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param attributes the implementation specific attributes of this declaration.
     * @param variables the variables of this variable declaration.
     */
    public VariableDeclaration(ILocation loc, Attribute[] attributes, VarList[] variables) {
        super(loc, attributes);
        this.variables = variables;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid VariableDeclaration: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("VariableDeclaration").append('[');
        if (variables == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < variables.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(variables[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the variables of this variable declaration.
     * @return the variables of this variable declaration.
     */
    public VarList[] getVariables() {
        return variables;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        if(variables!=null){
            children.addAll(Arrays.asList(variables));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Declaration)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(variables!=null){
                for (VarList elem : variables) {
                    elem.accept(visitor);
                }
            }
            if(attributes!=null){
                for (Attribute elem : attributes) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Declaration accept(GeneratedBoogieAstTransformer visitor) {
        Declaration node = visitor.transform(this);
        if(node != this){
            return node;
        }

        boolean isChanged=false;
            ArrayList<VarList> tmpListnewvariables = new ArrayList<>();
        if(variables != null){
            for(VarList elem : variables){
                VarList newvariables = (VarList)elem.accept(visitor);
                isChanged = isChanged || newvariables != elem;
                tmpListnewvariables.add(newvariables);
            }
        }
            ArrayList<Attribute> tmpListnewattributes = new ArrayList<>();
        if(attributes != null){
            for(Attribute elem : attributes){
                Attribute newattributes = (Attribute)elem.accept(visitor);
                isChanged = isChanged || newattributes != elem;
                tmpListnewattributes.add(newattributes);
            }
        }
        if(isChanged){
            return new VariableDeclaration(loc, tmpListnewattributes.toArray(new Attribute[0]), tmpListnewvariables.toArray(new VarList[0]));
        }
        return this;
    }
}
