/* VarList -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * Represents a list of names together with a type info, which is
 * used for declaration of constants, variables, function parameters
 * procedure parameters and logical variables.
 * For function parameters the identifier list must contain at most
 * one element (and zero means that the parameter has no name).
 * In any other case the identifier list must not be empty.
 * The where clause may only be present in procedures (but not
 * implementations) and in variable declarations.
 */
public class VarList extends BoogieASTNode {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(VarList.class);
    /**
     * the location of this node
     */
    ILocation loc;

    /**
     * The names of the declared identifiers. This can be
     * the empty array for unnamed function parameters. It should
     * never be null.
     */
    String[] identifiers;

    /**
     * The type of the declared identifiers.
     */
    ASTType type;

    /**
     * A where clause can restrict the type by a boolean expression.
     * The boolean expression usually mentions one of the identifiers
     * of the VarList. See the Boogie documentation for details.
     * A where clause may only appear at restricted places and its
     * semantics is sometimes a bit tricky.
     * This is <code>null</code> if there is no where clause present.
     * Note that in many places no where clause is allowed and this
     * must be <code>null</code>.
     */
    Expression whereClause;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param identifiers the names of the declared identifiers.
     * @param type the type of the declared identifiers.
     */
    public VarList(ILocation loc, String[] identifiers, ASTType type) {
        super(loc);
        this.loc = loc;
        this.identifiers = identifiers;
        this.type = type;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid VarList: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param identifiers the names of the declared identifiers.
     * @param type the type of the declared identifiers.
     * @param whereClause a where clause can restrict the type by a boolean expression.
     */
    public VarList(ILocation loc, String[] identifiers, ASTType type, Expression whereClause) {
        super(loc);
        this.loc = loc;
        this.identifiers = identifiers;
        this.type = type;
        this.whereClause = whereClause;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid VarList: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("VarList").append('[');
        sb.append(loc);
        sb.append(',');
        if (identifiers == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < identifiers.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(identifiers[i1]);
            }
            sb.append(']');
        }
        sb.append(',').append(type);
        sb.append(',').append(whereClause);
        return sb.append(']').toString();
    }

    /**
     * Gets the location of this node
     * @return the location of this node
     */
    public ILocation getLoc() {
        return loc;
    }

    /**
     * Sets the location of this node
     * @param loc the location of this node
     */
    public void setLoc(ILocation loc) {
        //Writeable only once
        if(this.loc != null && loc != this.loc){
                throw new AssertionError("Value is only writeable once");
        }
        this.loc = loc;
    }

    /**
     * Gets the names of the declared identifiers. This can be
     * the empty array for unnamed function parameters. It should
     * never be null.
     * @return the names of the declared identifiers.
     */
    public String[] getIdentifiers() {
        return identifiers;
    }

    /**
     * Gets the type of the declared identifiers.
     * @return the type of the declared identifiers.
     */
    public ASTType getType() {
        return type;
    }

    /**
     * Gets a where clause can restrict the type by a boolean expression.
     * The boolean expression usually mentions one of the identifiers
     * of the VarList. See the Boogie documentation for details.
     * A where clause may only appear at restricted places and its
     * semantics is sometimes a bit tricky.
     * This is <code>null</code> if there is no where clause present.
     * Note that in many places no where clause is allowed and this
     * must be <code>null</code>.
     * @return a where clause can restrict the type by a boolean expression.
     */
    public Expression getWhereClause() {
        return whereClause;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(type);
        children.add(whereClause);
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit(this)) {
            if(type!=null){
                type.accept(visitor);
            }
            if(whereClause!=null){
                whereClause.accept(visitor);
            }
        }
    }

    public VarList accept(GeneratedBoogieAstTransformer visitor) {
        VarList node = visitor.transform(this);
        if(node != this){
            return node;
        }

            ASTType newtype = null;
        if(type != null){
            newtype = (ASTType)type.accept(visitor);
        }
            Expression newwhereClause = null;
        if(whereClause != null){
            newwhereClause = (Expression)whereClause.accept(visitor);
        }
        if(type != newtype || whereClause != newwhereClause){
            return new VarList(loc, identifiers, newtype, newwhereClause);
        }
        return this;
    }
}
