/* WhileStatement -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.ILocation;
/**
 * A while statements. The condition is evaluated and as long as
 * it is true, the body is executed.
 * Note that the condition cannot have side-effects.
 */
public class WhileStatement extends Statement {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(WhileStatement.class);
    /**
     * The loop condition. This is a boolean expression. It can be
     * a {@link WildcardExpression} to indicate that the loop is taken
     * an arbitrary number of times.
     */
    Expression condition;

    /**
     * The invariants that hold at the beginning of every iteration.
     * I.e., it holds before the loop condition is evaluated (and also
     * afterwards since the condition has no side-effects).
     */
    LoopInvariantSpecification[] invariants;

    /**
     * The loop body.
     */
    Statement[] body;

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param condition the loop condition.
     * @param invariants the invariants that hold at the beginning of every iteration.
     * @param body the loop body.
     */
    public WhileStatement(ILocation loc, Expression condition, LoopInvariantSpecification[] invariants, Statement[] body) {
        super(loc);
        this.condition = condition;
        this.invariants = invariants;
        this.body = body;
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid WhileStatement: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("WhileStatement").append('[');
        sb.append(condition);
        sb.append(',');
        if (invariants == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < invariants.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(invariants[i1]);
            }
            sb.append(']');
        }
        sb.append(',');
        if (body == null) {
            sb.append("null");
        } else {
            sb.append('[');
            for(int i1 = 0; i1 < body.length; i1++) {
                if (i1 > 0) sb.append(',');
                    sb.append(body[i1]);
            }
            sb.append(']');
        }
        return sb.append(']').toString();
    }

    /**
     * Gets the loop condition. This is a boolean expression. It can be
     * a {@link WildcardExpression} to indicate that the loop is taken
     * an arbitrary number of times.
     * @return the loop condition.
     */
    public Expression getCondition() {
        return condition;
    }

    /**
     * Gets the invariants that hold at the beginning of every iteration.
     * I.e., it holds before the loop condition is evaluated (and also
     * afterwards since the condition has no side-effects).
     * @return the invariants that hold at the beginning of every iteration.
     */
    public LoopInvariantSpecification[] getInvariants() {
        return invariants;
    }

    /**
     * Gets the loop body.
     * @return the loop body.
     */
    public Statement[] getBody() {
        return body;
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        children.add(condition);
        if(invariants!=null){
            children.addAll(Arrays.asList(invariants));
        }
        if(body!=null){
            children.addAll(Arrays.asList(body));
        }
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Statement)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        if (visitor.visit(this)) {
            if(condition!=null){
                condition.accept(visitor);
            }
            if(invariants!=null){
                for (LoopInvariantSpecification elem : invariants) {
                    elem.accept(visitor);
                }
            }
            if(body!=null){
                for (Statement elem : body) {
                    elem.accept(visitor);
                }
            }
        }
    }

    public Statement accept(GeneratedBoogieAstTransformer visitor) {
        Statement node = visitor.transform(this);
        if(node != this){
            return node;
        }

            Expression newcondition = null;
        if(condition != null){
            newcondition = (Expression)condition.accept(visitor);
        }
        boolean isChanged=false;
            ArrayList<LoopInvariantSpecification> tmpListnewinvariants = new ArrayList<>();
        if(invariants != null){
            for(LoopInvariantSpecification elem : invariants){
                LoopInvariantSpecification newinvariants = (LoopInvariantSpecification)elem.accept(visitor);
                isChanged = isChanged || newinvariants != elem;
                tmpListnewinvariants.add(newinvariants);
            }
        }
            ArrayList<Statement> tmpListnewbody = new ArrayList<>();
        if(body != null){
            for(Statement elem : body){
                Statement newbody = (Statement)elem.accept(visitor);
                isChanged = isChanged || newbody != elem;
                tmpListnewbody.add(newbody);
            }
        }
        if(isChanged || condition != newcondition){
            return new WhileStatement(loc, newcondition, tmpListnewinvariants.toArray(new LoopInvariantSpecification[0]), tmpListnewbody.toArray(new Statement[0]));
        }
        return this;
    }
}
