/* WildcardExpression -- Automatically generated by TreeBuilder (2025-06-30T08:11Z) */

package ultimate.ast;

import java.util.List;

import ultimate.ast.BoogieASTNode;
import ultimate.models.IBoogieType;
import ultimate.models.ILocation;
/**
 * This can be used as call forall parameter, or as if or
 * while condition. In all other places it is forbidden.
 */
public class WildcardExpression extends Expression {
    private static final long serialVersionUID = 1L;
    private static final java.util.function.Predicate<BoogieASTNode> VALIDATOR = 
			BoogieASTNode.VALIDATORS.get(WildcardExpression.class);
    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     */
    public WildcardExpression(ILocation loc) {
        super(loc);
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid WildcardExpression: " + this;
    }

    /**
     * The constructor taking initial values.
     * @param loc the location of this node
     * @param type the type of this expression.
     */
    public WildcardExpression(ILocation loc, IBoogieType type) {
        super(loc, type);
        assert VALIDATOR == null || VALIDATOR.test(this) : "Invalid WildcardExpression: " + this;
    }

    /**
     * Returns a textual description of this object.
     */
    public String toString() {
        return "WildcardExpression";
    }

    public List<BoogieASTNode> getOutgoingNodes() {
        List<BoogieASTNode> children = super.getOutgoingNodes();
        return children;
    }

    public void accept(GeneratedBoogieAstVisitor visitor) {
        if (visitor.visit((Expression)this)) {
            //visit parent types higher up if necessary
        } else {
            return;
        }
        visitor.visit(this);
    }

    public Expression accept(GeneratedBoogieAstTransformer visitor) {
        Expression node = visitor.transform(this);
        if(node != this){
            return node;
        }

        return this;
    }
}
