
//----------------------------------------------------
// The following code was generated by jh-javacup-1.2 20210807
// Thu Jul 24 11:07:03 CEST 2025
//----------------------------------------------------

package ultimate.smtinterpol.dimacs;

/** CUP generated class containing symbol constants. */
public class LexerSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int PROBLEM = 2;
  public static final int CNF = 3;
  public static final int NOT = 4;
  public static final int EOC = 5;
  public static final int NUMBER = 6;
}

