
//----------------------------------------------------
// The following code was generated by jh-javacup-1.2 20210807
// Tue Nov 25 16:05:17 CET 2025
//----------------------------------------------------

package ultimate.smtsolver;

/** CUP generated class containing symbol constants. */
public class LexerSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int UNDERSCORE = 2;
  public static final int BANG = 3;
  public static final int AS = 4;
  public static final int ASSERT = 5;
  public static final int CHECKSAT = 6;
  public static final int CONTINUEDEXECUTION = 7;
  public static final int DECLARESORT = 8;
  public static final int DECLAREFUN = 9;
  public static final int DEFINESORT = 10;
  public static final int DEFINEFUN = 11;
  public static final int ERRORSYM = 12;
  public static final int EXISTS = 13;
  public static final int EXIT = 14;
  public static final int FALSE = 15;
  public static final int FORALL = 16;
  public static final int GETASSERTIONS = 17;
  public static final int GETASSIGNMENT = 18;
  public static final int GETINFO = 19;
  public static final int GETINTERPOLANTS = 20;
  public static final int GETMODEL = 21;
  public static final int GETOPTION = 22;
  public static final int GETPROOF = 23;
  public static final int GETUNSATCORE = 24;
  public static final int GETVALUE = 25;
  public static final int IMMEDIATEEXIT = 26;
  public static final int INCOMPLETE = 27;
  public static final int LET = 28;
  public static final int LOGIC = 29;
  public static final int NONE = 30;
  public static final int NUMERALSYM = 31;
  public static final int MEMOUT = 32;
  public static final int PAR = 33;
  public static final int POP = 34;
  public static final int PUSH = 35;
  public static final int DECIMALSYM = 36;
  public static final int SAT = 37;
  public static final int SUCCESS = 38;
  public static final int SETLOGIC = 39;
  public static final int SETINFO = 40;
  public static final int SETOPTION = 41;
  public static final int STRINGSYM = 42;
  public static final int THEORY = 43;
  public static final int TRUE = 44;
  public static final int UNKNOWN = 45;
  public static final int UNSUPPORTED = 46;
  public static final int UNSAT = 47;
  public static final int INCLUDE = 48;
  public static final int RESET = 49;
  public static final int SIMPLIFY = 50;
  public static final int TIMED = 51;
  public static final int TERM = 52;
  public static final int TIMEOUT = 53;
  public static final int ASSERTED = 54;
  public static final int STDOUT = 55;
  public static final int STDERR = 56;
  public static final int GETTERM = 57;
  public static final int CANCELED = 58;
  public static final int INTERPOLANTS = 59;
  public static final int CNAMED = 60;
  public static final int CPATTERN = 61;
  public static final int CSORTSDESCRIPTION = 62;
  public static final int CSORTS = 63;
  public static final int CFUNS = 64;
  public static final int CFUNSDESCRIPTION = 65;
  public static final int CDEFINITION = 66;
  public static final int CEXTENSIONS = 67;
  public static final int CLANGUAGE = 68;
  public static final int CTHEORIES = 69;
  public static final int CNOTES = 70;
  public static final int CVALUES = 71;
  public static final int CDIAGNOSTICOUTPUTCHANNEL = 72;
  public static final int CREGULAROUTPUTCHANNEL = 73;
  public static final int CEXPANDDEFINITIONS = 74;
  public static final int CINTERACTIVEMODE = 75;
  public static final int CPRINTSUCCESS = 76;
  public static final int CVERBOSITY = 77;
  public static final int CPRODUCEASSIGNMENTS = 78;
  public static final int CPRODUCEMODELS = 79;
  public static final int CPRODUCEPROOFS = 80;
  public static final int CPRODUCEUNSATCORES = 81;
  public static final int CRANDOMSEED = 82;
  public static final int CINTERPOLANTCHECKMODE = 83;
  public static final int CSTRONGSIMPLIFIER = 84;
  public static final int CTIMEOUT = 85;
  public static final int CERRORBEHAVIOR = 86;
  public static final int CNAME = 87;
  public static final int CAUTHORS = 88;
  public static final int CVERSION = 89;
  public static final int CSTATUS = 90;
  public static final int CREASONUNKNOWN = 91;
  public static final int CPIVOT = 92;
  public static final int CASSERTED = 93;
  public static final int SYMBOL = 94;
  public static final int KEYWORD = 95;
  public static final int NUMERAL = 96;
  public static final int DECIMAL = 97;
  public static final int HEXADECIMAL = 98;
  public static final int BINARY = 99;
  public static final int STRING = 100;
  public static final int LPAR = 101;
  public static final int RPAR = 102;
}

